
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Accounts
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Accounts()
    {

        this.EndOfDayPaymentAnalysis = new HashSet<EndOfDayPaymentAnalysis>();

        this.EndOfDayVoidsAnalysis = new HashSet<EndOfDayVoidsAnalysis>();

        this.EODAccountToPmsTransfer = new HashSet<EODAccountToPmsTransfer>();

        this.PosInfo = new HashSet<PosInfo>();

        this.PosInfoDetail_Excluded_Accounts = new HashSet<PosInfoDetail_Excluded_Accounts>();

        this.TablePaySuggestion = new HashSet<TablePaySuggestion>();

        this.Transactions = new HashSet<Transactions>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<short> Type { get; set; }

    public Nullable<bool> IsDefault { get; set; }

    public Nullable<bool> SendsTransfer { get; set; }

    public Nullable<bool> CardOnly { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<short> KeyboardType { get; set; }

    public Nullable<long> PMSPaymentId { get; set; }

    public Nullable<long> DAId { get; set; }

    public Nullable<int> Sort { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EndOfDayPaymentAnalysis> EndOfDayPaymentAnalysis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EndOfDayVoidsAnalysis> EndOfDayVoidsAnalysis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EODAccountToPmsTransfer> EODAccountToPmsTransfer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo> PosInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfoDetail_Excluded_Accounts> PosInfoDetail_Excluded_Accounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TablePaySuggestion> TablePaySuggestion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transactions> Transactions { get; set; }

}

}
