
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class AllowedMealsPerBoard
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AllowedMealsPerBoard()
    {

        this.AllowedMealsPerBoardDetails = new HashSet<AllowedMealsPerBoardDetails>();

    }


    public long Id { get; set; }

    public string BoardId { get; set; }

    public string BoardDescription { get; set; }

    public Nullable<int> AllowedMeals { get; set; }

    public Nullable<decimal> AllowedDiscountAmount { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<int> AllowedMealsChild { get; set; }

    public Nullable<decimal> AllowedDiscountAmountChild { get; set; }



    public virtual Pricelist Pricelist { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AllowedMealsPerBoardDetails> AllowedMealsPerBoardDetails { get; set; }

}

}
