
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class BoardMeals
{

    public long Id { get; set; }

    public string BoardId { get; set; }

    public string BoardDescription { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<int> MealsQty { get; set; }

    public string BoardCode { get; set; }



    public virtual Product Product { get; set; }

}

}
