
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ClientPos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ClientPos()
    {

        this.Invoices = new HashSet<Invoices>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public string Theme { get; set; }

    public Nullable<bool> LogInToOrder { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual PosInfo PosInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
