
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Combo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Combo()
    {

        this.ComboDetail = new HashSet<ComboDetail>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<long> ProductComboId { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }



    public virtual Department Department { get; set; }

    public virtual Product Product { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComboDetail> ComboDetail { get; set; }

}

}
