
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class CreditTransactions_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<long> CreditAccountId { get; set; }

    public Nullable<long> CreditCodeId { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<System.DateTime> CreationTS { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<long> StaffId { get; set; }

    public string Description { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> InvoiceId { get; set; }

    public Nullable<long> TransactionId { get; set; }

}

}
