
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class CreditTransactions
{

    public long Id { get; set; }

    public Nullable<long> CreditAccountId { get; set; }

    public Nullable<long> CreditCodeId { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<System.DateTime> CreationTS { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<long> StaffId { get; set; }

    public string Description { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> InvoiceId { get; set; }

    public Nullable<long> TransactionId { get; set; }



    public virtual CreditAccounts CreditAccounts { get; set; }

    public virtual CreditCodes CreditCodes { get; set; }

    public virtual EndOfDay EndOfDay { get; set; }

    public virtual PosInfo PosInfo { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Transactions Transactions { get; set; }

    public virtual Invoices Invoices { get; set; }

}

}
