
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class CreditAccounts
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CreditAccounts()
    {

        this.CreditCodes = new HashSet<CreditCodes>();

        this.CreditTransactions = new HashSet<CreditTransactions>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<System.DateTime> ActivateTS { get; set; }

    public Nullable<System.DateTime> DeactivateTS { get; set; }



    public virtual EndOfDay EndOfDay { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditCodes> CreditCodes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

}

}
