
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class CreditCodes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CreditCodes()
    {

        this.CreditTransactions = new HashSet<CreditTransactions>();

        this.TablePaySuggestion = new HashSet<TablePaySuggestion>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string Code { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<long> CreditAccountId { get; set; }



    public virtual CreditAccounts CreditAccounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TablePaySuggestion> TablePaySuggestion { get; set; }

}

}
