
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_Addresses
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DA_Addresses()
    {

        this.DA_Orders = new HashSet<DA_Orders>();

        this.DA_Stores = new HashSet<DA_Stores>();

    }


    public long Id { get; set; }

    public int OwnerId { get; set; }

    public string AddressStreet { get; set; }

    public string AddressNo { get; set; }

    public string VerticalStreet { get; set; }

    public string Floor { get; set; }

    public string Area { get; set; }

    public string City { get; set; }

    public string Zipcode { get; set; }

    public double Latitude { get; set; }

    public double Longtitude { get; set; }

    public string Notes { get; set; }

    public string Bell { get; set; }

    public int AddressType { get; set; }

    public string ExtObj { get; set; }

    public string ExtId1 { get; set; }

    public string ExtId2 { get; set; }

    public string FriendlyName { get; set; }

    public Nullable<int> AddressProximity { get; set; }

    public bool IsDeleted { get; set; }

    public string LastPhoneNumber { get; set; }

    public string Phonetics { get; set; }

    public string PhoneticsArea { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_Orders> DA_Orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_Stores> DA_Stores { get; set; }

}

}
