
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_CustomerMessages
{

    public long Id { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public Nullable<long> MessageId { get; set; }

    public Nullable<long> MessageDetailsId { get; set; }

    public Nullable<long> MainDAMessageId { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public Nullable<long> StaffId { get; set; }

    public string MessageText { get; set; }

    public Nullable<long> OrderId { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<bool> IsTemporary { get; set; }



    public virtual DA_Customers DA_Customers { get; set; }

    public virtual DA_MainMessages DA_MainMessages { get; set; }

    public virtual DA_Messages DA_Messages { get; set; }

    public virtual DA_MessagesDetails DA_MessagesDetails { get; set; }

    public virtual DA_Orders DA_Orders { get; set; }

    public virtual DA_Stores DA_Stores { get; set; }

}

}
