
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_GeoPolygonsDetails
{

    public long Id { get; set; }

    public long PolygId { get; set; }

    public double Latitude { get; set; }

    public double Longtitude { get; set; }



    public virtual DA_GeoPolygons DA_GeoPolygons { get; set; }

}

}
