
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_GeoPolygons
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DA_GeoPolygons()
    {

        this.DA_GeoPolygonsDetails = new HashSet<DA_GeoPolygonsDetails>();

    }


    public long Id { get; set; }

    public Nullable<long> StoreId { get; set; }

    public string Name { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }



    public virtual DA_Stores DA_Stores { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_GeoPolygonsDetails> DA_GeoPolygonsDetails { get; set; }

}

}
