
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_LoyalPoints
{

    public long Id { get; set; }

    public long CustomerId { get; set; }

    public int Points { get; set; }

    public System.DateTime Date { get; set; }

    public long OrderId { get; set; }

    public long StoreId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public string Description { get; set; }



    public virtual DA_Customers DA_Customers { get; set; }

    public virtual Staff Staff { get; set; }

}

}
