
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_LoyalRedeemFreeProduct
{

    public long Id { get; set; }

    public int Points { get; set; }

    public Nullable<long> ProductId { get; set; }

    public string ProductName { get; set; }

    public Nullable<long> ProdCategoryId { get; set; }

    public string ProdCategoryName { get; set; }

    public decimal Qnt { get; set; }



    public virtual Product Product { get; set; }

    public virtual ProductCategories ProductCategories { get; set; }

}

}
