
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_LoyalConfig
{

    public short GainPointsType { get; set; }

    public short RedeemType { get; set; }

    public int MaxPoints { get; set; }

    public int ExpDuration { get; set; }

    public decimal MinAmount { get; set; }

    public Nullable<int> InitPoints { get; set; }

}

}
