
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_MainMessages
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DA_MainMessages()
    {

        this.DA_CustomerMessages = new HashSet<DA_CustomerMessages>();

        this.DA_Messages = new HashSet<DA_Messages>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string Email { get; set; }

    public Nullable<bool> OnOrderCreate { get; set; }

    public Nullable<bool> OnOrderUpdate { get; set; }

    public Nullable<bool> OnNewCall { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_CustomerMessages> DA_CustomerMessages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_Messages> DA_Messages { get; set; }

}

}
