
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_OrderDetailsExtras
{

    public long Id { get; set; }

    public long OrderDetailId { get; set; }

    public long ExtrasId { get; set; }

    public string Description { get; set; }

    public decimal Qnt { get; set; }

    public decimal Price { get; set; }

    public decimal TotalVat { get; set; }

    public decimal RateVat { get; set; }

    public decimal RateTax { get; set; }

    public decimal TotalTax { get; set; }

    public decimal NetAmount { get; set; }

    public string ExtrasCode { get; set; }



    public virtual DA_OrderDetails DA_OrderDetails { get; set; }

}

}
