
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_OrderDetails
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DA_OrderDetails()
    {

        this.DA_OrderDetailsExtras = new HashSet<DA_OrderDetailsExtras>();

    }


    public long Id { get; set; }

    public long DAOrderId { get; set; }

    public long ProductId { get; set; }

    public string Description { get; set; }

    public long PriceListId { get; set; }

    public decimal Price { get; set; }

    public decimal Qnt { get; set; }

    public decimal Discount { get; set; }

    public decimal Total { get; set; }

    public decimal TotalVat { get; set; }

    public decimal RateVat { get; set; }

    public decimal RateTax { get; set; }

    public decimal TotalTax { get; set; }

    public decimal NetAmount { get; set; }

    public string ItemRemark { get; set; }

    public string ProductCode { get; set; }

    public Nullable<short> OtherDiscount { get; set; }



    public virtual Product Product { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_OrderDetailsExtras> DA_OrderDetailsExtras { get; set; }

    public virtual DA_Orders DA_Orders { get; set; }

}

}
