
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_OrderStatus
{

    public long Id { get; set; }

    public long OrderDAId { get; set; }

    public short Status { get; set; }

    public System.DateTime StatusDate { get; set; }



    public virtual DA_Orders DA_Orders { get; set; }

}

}
