
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_ScheduledTaskes
{

    public long Id { get; set; }

    public string StoreFullURL { get; set; }

    public long TableId { get; set; }

    public long StoreId { get; set; }

    public int Action { get; set; }

    public int Short { get; set; }

    public int FaildNo { get; set; }

}

}
