
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DA_Stores
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DA_Stores()
    {

        this.DA_GeoPolygons = new HashSet<DA_GeoPolygons>();

        this.DA_ShortageProds = new HashSet<DA_ShortageProds>();

        this.DAStore_PriceListAssoc = new HashSet<DAStore_PriceListAssoc>();

        this.DA_Orders = new HashSet<DA_Orders>();

        this.DA_CustomerMessages = new HashSet<DA_CustomerMessages>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Title2 { get; set; }

    public string Notes { get; set; }

    public int DeliveryTime { get; set; }

    public int TakeOutTime { get; set; }

    public string Description { get; set; }

    public string Description2 { get; set; }

    public string Doy { get; set; }

    public string VatNo { get; set; }

    public string Email { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public Nullable<long> AddressId { get; set; }

    public string Image { get; set; }

    public string Thumbnail { get; set; }

    public string WebApi { get; set; }

    public int PosId { get; set; }

    public string StoreId { get; set; }

    public int PosStaffId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public short StoreStatus { get; set; }

    public string RGB { get; set; }

    public string CronScheduler { get; set; }

    public Nullable<bool> isAllowedToHaveCreditCard { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_GeoPolygons> DA_GeoPolygons { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_ShortageProds> DA_ShortageProds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DAStore_PriceListAssoc> DAStore_PriceListAssoc { get; set; }

    public virtual DA_Addresses DA_Addresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_Orders> DA_Orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_CustomerMessages> DA_CustomerMessages { get; set; }

}

}
