
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Delivery_CustomersPhonesAndAddress
{

    public long ID { get; set; }

    public long CustomerID { get; set; }

    public long PhoneID { get; set; }

    public long AddressID { get; set; }

    public short IsShipping { get; set; }



    public virtual Delivery_Customers Delivery_Customers { get; set; }

    public virtual Delivery_CustomersPhones Delivery_CustomersPhones { get; set; }

}

}
