
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Delivery_CustomersShippingAddress
{

    public long ID { get; set; }

    public long CustomerID { get; set; }

    public string AddressStreet { get; set; }

    public string AddressNo { get; set; }

    public string City { get; set; }

    public string Zipcode { get; set; }

    public Nullable<int> Type { get; set; }

    public string Latitude { get; set; }

    public string Longtitude { get; set; }

    public string Floor { get; set; }

    public Nullable<bool> IsSelected { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string ExtKey { get; set; }

    public Nullable<int> ExtType { get; set; }

    public string ExtObj { get; set; }

    public string ExtId1 { get; set; }

    public string ExtId2 { get; set; }

    public string VerticalStreet { get; set; }

    public string Notes { get; set; }



    public virtual Delivery_AddressTypes Delivery_AddressTypes { get; set; }

    public virtual Delivery_Customers Delivery_Customers { get; set; }

}

}
