
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Delivery_AddressTypes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Delivery_AddressTypes()
    {

        this.Delivery_CustomersBillingAddress = new HashSet<Delivery_CustomersBillingAddress>();

        this.Delivery_CustomersShippingAddress = new HashSet<Delivery_CustomersShippingAddress>();

    }


    public int ID { get; set; }

    public string Descr { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersBillingAddress> Delivery_CustomersBillingAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersShippingAddress> Delivery_CustomersShippingAddress { get; set; }

}

}
