
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class DeliveryRoutingHist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> Orders { get; set; }

    public Nullable<long> StaffId { get; set; }

    public string StaffName { get; set; }

    public Nullable<System.DateTime> AssignDate { get; set; }

    public Nullable<System.DateTime> AcceptDate { get; set; }

    public string RejectedNames { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> AssignStatus { get; set; }

    public Nullable<System.DateTime> ReturnDate { get; set; }

    public Nullable<bool> Failure3th { get; set; }

}

}
