
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Delivery_Customers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Delivery_Customers()
    {

        this.Delivery_CustomersBillingAddress = new HashSet<Delivery_CustomersBillingAddress>();

        this.Delivery_CustomersPhones = new HashSet<Delivery_CustomersPhones>();

        this.Delivery_CustomersPhonesAndAddress = new HashSet<Delivery_CustomersPhonesAndAddress>();

        this.Delivery_CustomersShippingAddress = new HashSet<Delivery_CustomersShippingAddress>();

        this.Invoice_Guests_Trans = new HashSet<Invoice_Guests_Trans>();

    }


    public long ID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string VatNo { get; set; }

    public string DOY { get; set; }

    public string Floor { get; set; }

    public string email { get; set; }

    public string Comments { get; set; }

    public Nullable<int> CustomerType { get; set; }

    public string BillingName { get; set; }

    public string BillingVatNo { get; set; }

    public string BillingDOY { get; set; }

    public string BillingJob { get; set; }

    public Nullable<long> DefaultPricelistId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string ExtCustId { get; set; }

    public Nullable<int> ExtType { get; set; }

    public string ExtObj { get; set; }

    public Nullable<bool> GDPR_IsDeleted { get; set; }

    public Nullable<bool> GDPR_Marketing { get; set; }

    public Nullable<bool> GDPR_Returner { get; set; }

    public Nullable<bool> GDPR_StaffId { get; set; }

    public Nullable<bool> GDPR_StaffName { get; set; }

    public string PhoneComp { get; set; }

    public Nullable<bool> SendSms { get; set; }

    public Nullable<bool> SendEmail { get; set; }

    public string Proffesion { get; set; }



    public virtual Delivery_CustomersTypes Delivery_CustomersTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersBillingAddress> Delivery_CustomersBillingAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersPhones> Delivery_CustomersPhones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersPhonesAndAddress> Delivery_CustomersPhonesAndAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Delivery_CustomersShippingAddress> Delivery_CustomersShippingAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Guests_Trans> Invoice_Guests_Trans { get; set; }

}

}
