
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class EmailConfig
{

    public long Id { get; set; }

    public string Smtp { get; set; }

    public int Port { get; set; }

    public bool Ssl { get; set; }

    public string Username { get; set; }

    public string Sender { get; set; }

    public byte[] Password { get; set; }

    public bool IsActive { get; set; }

}

}
