
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class EndOfDayDetail
{

    public long Id { get; set; }

    public Nullable<long> EndOfdayId { get; set; }

    public Nullable<long> VatId { get; set; }

    public Nullable<decimal> VatRate { get; set; }

    public Nullable<decimal> VatAmount { get; set; }

    public Nullable<long> TaxId { get; set; }

    public Nullable<decimal> TaxAmount { get; set; }

    public Nullable<decimal> Gross { get; set; }

    public Nullable<decimal> Net { get; set; }

    public Nullable<decimal> Discount { get; set; }



    public virtual EndOfDay EndOfDay { get; set; }

    public virtual Tax Tax { get; set; }

    public virtual Vat Vat { get; set; }

}

}
