
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ForexService
{

    public long Id { get; set; }

    public string CurFrom { get; set; }

    public string CurTo { get; set; }

    public Nullable<decimal> Rate { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

}

}
