
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Guest()
    {

        this.Invoice_Guests_Trans = new HashSet<Invoice_Guests_Trans>();

        this.MealConsumption = new HashSet<MealConsumption>();

        this.OrderDetail = new HashSet<OrderDetail>();

        this.TablePaySuggestion = new HashSet<TablePaySuggestion>();

        this.Invoices = new HashSet<Invoices>();

    }


    public long Id { get; set; }

    public Nullable<System.DateTime> arrivalDT { get; set; }

    public Nullable<System.DateTime> departureDT { get; set; }

    public Nullable<System.DateTime> birthdayDT { get; set; }

    public string Room { get; set; }

    public Nullable<int> RoomId { get; set; }

    public string Arrival { get; set; }

    public string Departure { get; set; }

    public string ReservationCode { get; set; }

    public Nullable<int> ProfileNo { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Member { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Birthday { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public string VIP { get; set; }

    public string Benefits { get; set; }

    public string NationalityCode { get; set; }

    public string ConfirmationCode { get; set; }

    public Nullable<int> Type { get; set; }

    public string Title { get; set; }

    public Nullable<int> Adults { get; set; }

    public Nullable<int> Children { get; set; }

    public string BoardCode { get; set; }

    public string BoardName { get; set; }

    public string Note1 { get; set; }

    public string Note2 { get; set; }

    public Nullable<int> ReservationId { get; set; }

    public Nullable<bool> IsSharer { get; set; }

    public Nullable<long> HotelId { get; set; }

    public Nullable<int> ClassId { get; set; }

    public string ClassName { get; set; }

    public Nullable<int> AvailablePoints { get; set; }

    public Nullable<int> fnbdiscount { get; set; }

    public Nullable<int> ratebuy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Guests_Trans> Invoice_Guests_Trans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MealConsumption> MealConsumption { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TablePaySuggestion> TablePaySuggestion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
