
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class HitPosOrders
{

    public long CurId { get; set; }

    public int id { get; set; }

    public Nullable<int> orderno { get; set; }

    public Nullable<int> pos { get; set; }

    public string shop_id { get; set; }

    public Nullable<int> item_group { get; set; }

    public Nullable<int> item_code { get; set; }

    public string item_descr { get; set; }

    public Nullable<int> item_subgroup { get; set; }

    public Nullable<int> item_vat { get; set; }

    public Nullable<decimal> cont_line { get; set; }

    public string sp { get; set; }

    public Nullable<System.DateTime> prep_time { get; set; }

    public Nullable<System.DateTime> start_time { get; set; }

    public Nullable<int> load_time { get; set; }

    public Nullable<int> otd { get; set; }

    public Nullable<int> qty { get; set; }

    public Nullable<int> amount { get; set; }

    public Nullable<int> total { get; set; }

    public Nullable<int> waiter { get; set; }

    public Nullable<int> ttable { get; set; }

    public Nullable<int> listino { get; set; }

    public Nullable<int> receipt { get; set; }

    public string member { get; set; }

    public Nullable<int> priority { get; set; }

    public Nullable<int> kdws { get; set; }

    public Nullable<int> ready { get; set; }

    public Nullable<int> rqty { get; set; }

    public Nullable<int> nieko_flag { get; set; }

    public Nullable<int> status { get; set; }

    public Nullable<System.DateTime> status_time { get; set; }

    public Nullable<int> rest_time { get; set; }

    public string room { get; set; }

    public string payment { get; set; }

    public string type { get; set; }

    public string comments { get; set; }

    public Nullable<int> mqty { get; set; }

    public Nullable<System.DateTime> rec_time_start { get; set; }

    public Nullable<System.DateTime> status_time2 { get; set; }

    public Nullable<System.DateTime> status_time3 { get; set; }

    public Nullable<System.DateTime> status_time4 { get; set; }

    public Nullable<System.DateTime> status_time5 { get; set; }

    public Nullable<System.DateTime> fo_day { get; set; }

    public Nullable<System.DateTime> delivery_time { get; set; }

    public Nullable<int> agent { get; set; }

    public Nullable<int> flag_up { get; set; }

    public Nullable<int> sent { get; set; }

    public Nullable<int> correct { get; set; }

    public Nullable<int> completed { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

}

}
