
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class HitPosCustomers
{

    public long CurId { get; set; }

    public string customerid { get; set; }

    public string name { get; set; }

    public string fname { get; set; }

    public string title { get; set; }

    public string profession { get; set; }

    public string tel1 { get; set; }

    public string tel2 { get; set; }

    public string fax { get; set; }

    public string mobile { get; set; }

    public string address1 { get; set; }

    public string address2 { get; set; }

    public string address_no { get; set; }

    public string orofos1 { get; set; }

    public string orofos2 { get; set; }

    public string city { get; set; }

    public string zipcode { get; set; }

    public string doy { get; set; }

    public string afm { get; set; }

    public string email { get; set; }

    public string contact { get; set; }

    public string vip { get; set; }

    public string member { get; set; }

    public string tomeas { get; set; }

    public string store { get; set; }

    public string sector { get; set; }

    public string diet { get; set; }

    public string entolh { get; set; }

    public string farsa { get; set; }

    public string remarks { get; set; }

    public Nullable<double> amount { get; set; }

    public Nullable<System.DateTime> expireddate { get; set; }

    public string order_comments { get; set; }

    public Nullable<System.DateTime> first_order { get; set; }

    public Nullable<System.DateTime> last_order { get; set; }

    public Nullable<int> no_of_orders { get; set; }

    public Nullable<decimal> tziros { get; set; }

    public Nullable<int> bonus { get; set; }

    public Nullable<int> epitages { get; set; }

    public Nullable<int> zerobonus { get; set; }

    public Nullable<int> domino_false { get; set; }

    public Nullable<int> lates { get; set; }

    public Nullable<decimal> credit { get; set; }

    public Nullable<decimal> max_charge { get; set; }

    public string company_name { get; set; }

    public string bl_address { get; set; }

    public string bl_address_no { get; set; }

    public string bl_city { get; set; }

    public Nullable<int> doycode { get; set; }

}

}
