
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class HotelInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HotelInfo()
    {

        this.TR_Config = new HashSet<TR_Config>();

        this.TR_ReservationCustomers = new HashSet<TR_ReservationCustomers>();

    }


    public long Id { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<int> HotelId { get; set; }

    public string HotelUri { get; set; }

    public Nullable<byte> Type { get; set; }

    public string RedirectToCustomerCard { get; set; }

    public Nullable<short> PmsType { get; set; }

    public string DBUserName { get; set; }

    public string DBPassword { get; set; }

    public string HotelName { get; set; }

    public string ServerName { get; set; }

    public Nullable<short> MPEHotel { get; set; }

    public string DBName { get; set; }

    public Nullable<short> allHotels { get; set; }

    public string HotelType { get; set; }



    public virtual Store Store { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_Config> TR_Config { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_ReservationCustomers> TR_ReservationCustomers { get; set; }

}

}
