
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Ingredient_ProdCategoryAssoc
{

    public long Id { get; set; }

    public Nullable<long> IngredientId { get; set; }

    public Nullable<long> ProductCategoryId { get; set; }

    public Nullable<long> Sort { get; set; }

    public Nullable<long> DAId { get; set; }

    public Nullable<double> MinQty { get; set; }

    public Nullable<double> MaxQty { get; set; }

    public Nullable<bool> CanSavePrice { get; set; }

}

}
