
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Ingredients
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ingredients()
    {

        this.OrderDetailIgredients = new HashSet<OrderDetailIgredients>();

        this.PricelistDetail = new HashSet<PricelistDetail>();

        this.ProductExtras = new HashSet<ProductExtras>();

        this.ProductRecipe = new HashSet<ProductRecipe>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string ExtendedDescription { get; set; }

    public string SalesDescription { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> ItemId { get; set; }

    public Nullable<long> UnitId { get; set; }

    public string Code { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string Background { get; set; }

    public string Color { get; set; }

    public Nullable<long> IngredientCategoryId { get; set; }

    public Nullable<long> DAId { get; set; }

    public Nullable<bool> DisplayOnKds { get; set; }



    public virtual IngredientCategories IngredientCategories { get; set; }

    public virtual Items Items { get; set; }

    public virtual Units Units { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailIgredients> OrderDetailIgredients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PricelistDetail> PricelistDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductExtras> ProductExtras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductRecipe> ProductRecipe { get; set; }

}

}
