
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Invoices
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Invoices()
    {

        this.CreditTransactions = new HashSet<CreditTransactions>();

        this.Invoice_Guests_Trans = new HashSet<Invoice_Guests_Trans>();

        this.InvoiceShippingDetails = new HashSet<InvoiceShippingDetails>();

        this.Loyalty = new HashSet<Loyalty>();

        this.OrderDetailInvoices = new HashSet<OrderDetailInvoices>();

        this.Transactions = new HashSet<Transactions>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<long> InvoiceTypeId { get; set; }

    public Nullable<int> Counter { get; set; }

    public Nullable<System.DateTime> Day { get; set; }

    public Nullable<bool> IsPrinted { get; set; }

    public Nullable<long> GuestId { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> Vat { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public Nullable<decimal> Net { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<int> Cover { get; set; }

    public Nullable<long> TableId { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> PdaModuleId { get; set; }

    public Nullable<long> ClientPosId { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> PosInfoDetailId { get; set; }

    public Nullable<bool> IsVoided { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string DiscountRemark { get; set; }

    public string PaymentsDesc { get; set; }

    public short IsPaid { get; set; }

    public Nullable<decimal> PaidTotal { get; set; }

    public string Rooms { get; set; }

    public string OrderNo { get; set; }

    public bool IsInvoiced { get; set; }

    public string Hashcode { get; set; }

    public Nullable<decimal> TableSum { get; set; }

    public string CashAmount { get; set; }

    public string BuzzerNumber { get; set; }

    public Nullable<decimal> LoyaltyDiscount { get; set; }

    public string ForeignExchangeCurrency { get; set; }

    public Nullable<decimal> ForeignExchangeTotal { get; set; }

    public Nullable<decimal> ForeignExchangeDiscount { get; set; }

    public string ExtECRCode { get; set; }

    public string CustomersId { get; set; }

    public string ReservationsId { get; set; }



    public virtual ClientPos ClientPos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

    public virtual EndOfDay EndOfDay { get; set; }

    public virtual Guest Guest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Guests_Trans> Invoice_Guests_Trans { get; set; }

    public virtual InvoiceTypes InvoiceTypes { get; set; }

    public virtual PdaModule PdaModule { get; set; }

    public virtual PosInfo PosInfo { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Table Table { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvoiceShippingDetails> InvoiceShippingDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Loyalty> Loyalty { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transactions> Transactions { get; set; }

}

}
