
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Items
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Items()
    {

        this.Ingredients = new HashSet<Ingredients>();

        this.ProductExtras = new HashSet<ProductExtras>();

        this.ProductRecipe = new HashSet<ProductRecipe>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string ExtendedDescription { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> UnitId { get; set; }

    public Nullable<long> VatId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ingredients> Ingredients { get; set; }

    public virtual Units Units { get; set; }

    public virtual Vat Vat { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductExtras> ProductExtras { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductRecipe> ProductRecipe { get; set; }

}

}
