
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class KitchenInstructionLogger_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<long> KicthcenInstuctionId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<long> PdaModulId { get; set; }

    public Nullable<long> ClientId { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<System.DateTime> SendTS { get; set; }

    public Nullable<System.DateTime> ReceivedTS { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<short> Status { get; set; }

    public Nullable<long> TableId { get; set; }

    public string ExtecrName { get; set; }

    public string Description { get; set; }

}

}
