
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class KitchenInstruction
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KitchenInstruction()
    {

        this.KitchenInstructionLogger = new HashSet<KitchenInstructionLogger>();

        this.PosInfo_KitchenInstruction_Assoc = new HashSet<PosInfo_KitchenInstruction_Assoc>();

    }


    public long Id { get; set; }

    public Nullable<long> KitchenId { get; set; }

    public string Message { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KitchenInstructionLogger> KitchenInstructionLogger { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_KitchenInstruction_Assoc> PosInfo_KitchenInstruction_Assoc { get; set; }

}

}
