
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Lockers_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<bool> HasLockers { get; set; }

    public Nullable<double> TotalLockers { get; set; }

    public Nullable<double> TotalLockersAmount { get; set; }

    public Nullable<double> Paidlockers { get; set; }

    public Nullable<decimal> PaidlockersAmount { get; set; }

    public Nullable<decimal> OccLockers { get; set; }

    public Nullable<decimal> OccLockersAmount { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public int TotalCash { get; set; }

    public int TotalSplashCash { get; set; }

    public int ReturnCash { get; set; }

    public int ReturnSplashCash { get; set; }

    public int CloseCash { get; set; }

    public int CloseSplashCash { get; set; }

}

}
