
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Lockers
{

    public long Id { get; set; }

    public bool HasLockers { get; set; }

    public double TotalLockers { get; set; }

    public double TotalLockersAmount { get; set; }

    public double Paidlockers { get; set; }

    public decimal PaidlockersAmount { get; set; }

    public decimal OccLockers { get; set; }

    public decimal OccLockersAmount { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public int TotalCash { get; set; }

    public int TotalSplashCash { get; set; }

    public int ReturnCash { get; set; }

    public int ReturnSplashCash { get; set; }

    public int CloseCash { get; set; }

    public int CloseSplashCash { get; set; }



    public virtual EndOfDay EndOfDay { get; set; }

    public virtual PosInfo PosInfo { get; set; }

}

}
