
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Loyalty
{

    public long Id { get; set; }

    public System.DateTime Day { get; set; }

    public string LoyalltyId { get; set; }

    public string CouponCode { get; set; }

    public string GiftcardCode { get; set; }

    public string CouponType { get; set; }

    public string Campaign { get; set; }

    public string Channel { get; set; }

    public Nullable<long> InvoicesId { get; set; }

    public string ErrorDescription { get; set; }

    public string GiftCardCouponType { get; set; }

    public string GiftCardCampaign { get; set; }

    public Nullable<long> DAOrderId { get; set; }



    public virtual DA_Orders DA_Orders { get; set; }

    public virtual Invoices Invoices { get; set; }

}

}
