
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class MealConsumption_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<long> GuestId { get; set; }

    public Nullable<int> ConsumedMeals { get; set; }

    public Nullable<System.DateTime> ConsumedTS { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string BoardCode { get; set; }

    public Nullable<int> ReservationId { get; set; }

    public Nullable<int> ConsumedMealsChild { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public string Timezone { get; set; }

    public string Room { get; set; }

    public Nullable<int> HotelId { get; set; }

    public Nullable<long> StaffId { get; set; }

}

}
