
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class MetadataTable
{

    public long Id { get; set; }

    public Nullable<long> ReportType { get; set; }

    public string FieldName { get; set; }

    public string Description { get; set; }

    public Nullable<short> FieldType { get; set; }

    public string DefaultStyle { get; set; }

    public Nullable<bool> Summable { get; set; }

    public string Expression { get; set; }

}

}
