
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class NFCcard
{

    public long Id { get; set; }

    public Nullable<short> Type { get; set; }

    public Nullable<int> RoomSector { get; set; }

    public Nullable<int> FirstDateSector { get; set; }

    public Nullable<int> SecondDateSector { get; set; }

    public Nullable<bool> ValidateDate { get; set; }

}

}
