
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Notifications
{

    public long Id { get; set; }

    public string Message { get; set; }

    public Nullable<System.DateTime> MessageTS { get; set; }

    public string UserList { get; set; }

    public string Sender { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> StoreId { get; set; }



    public virtual PosInfo PosInfo { get; set; }

    public virtual Store Store { get; set; }

}

}
