
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetailIgredients
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OrderDetailIgredients()
    {

        this.OrderDetailInvoices = new HashSet<OrderDetailInvoices>();

        this.OrderDetailIgredientVatAnal = new HashSet<OrderDetailIgredientVatAnal>();

    }


    public long Id { get; set; }

    public Nullable<long> IngredientId { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> UnitId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> OrderDetailId { get; set; }

    public Nullable<long> PriceListDetailId { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> TotalAfterDiscount { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<double> PendingQty { get; set; }



    public virtual Ingredients Ingredients { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    public virtual PricelistDetail PricelistDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailIgredientVatAnal> OrderDetailIgredientVatAnal { get; set; }

}

}
