
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OrderDetail()
    {

        this.OrderDetailIgredients = new HashSet<OrderDetailIgredients>();

        this.OrderDetailInvoices = new HashSet<OrderDetailInvoices>();

        this.OrderDetailVatAnal = new HashSet<OrderDetailVatAnal>();

        this.TablePaySuggestion = new HashSet<TablePaySuggestion>();

    }


    public long Id { get; set; }

    public Nullable<long> OrderId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> KitchenId { get; set; }

    public Nullable<long> KdsId { get; set; }

    public Nullable<int> PreparationTime { get; set; }

    public Nullable<long> TableId { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<System.DateTime> StatusTS { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> PriceListDetailId { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<byte> PaidStatus { get; set; }

    public Nullable<long> TransactionId { get; set; }

    public Nullable<decimal> TotalAfterDiscount { get; set; }

    public Nullable<long> GuestId { get; set; }

    public Nullable<int> Couver { get; set; }

    public Nullable<System.Guid> Guid { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<double> PendingQty { get; set; }

    public Nullable<short> OtherDiscount { get; set; }

    public Nullable<int> KitchenStatus { get; set; }



    public virtual Guest Guest { get; set; }

    public virtual Order Order { get; set; }

    public virtual PricelistDetail PricelistDetail { get; set; }

    public virtual Product Product { get; set; }

    public virtual SalesType SalesType { get; set; }

    public virtual Table Table { get; set; }

    public virtual Transactions Transactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailIgredients> OrderDetailIgredients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailVatAnal> OrderDetailVatAnal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TablePaySuggestion> TablePaySuggestion { get; set; }

}

}
