
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<long> OrderId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> KitchenId { get; set; }

    public Nullable<long> KdsId { get; set; }

    public Nullable<int> PreparationTime { get; set; }

    public Nullable<long> TableId { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<System.DateTime> StatusTS { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> PriceListDetailId { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<byte> PaidStatus { get; set; }

    public Nullable<long> TransactionId { get; set; }

    public Nullable<decimal> TotalAfterDiscount { get; set; }

    public Nullable<long> GuestId { get; set; }

    public Nullable<int> Couver { get; set; }

    public Nullable<System.Guid> Guid { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<double> PendingQty { get; set; }

}

}
