
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetailIgredients_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<long> IngredientId { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> UnitId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> OrderDetailId { get; set; }

    public Nullable<long> PriceListDetailId { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> TotalAfterDiscount { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
