
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PageButtonDetail
{

    public long Id { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<bool> IsRequired { get; set; }

    public Nullable<double> MinQty { get; set; }

    public Nullable<double> MaxQty { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> AddCost { get; set; }

    public Nullable<decimal> RemoveCost { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<short> Sort { get; set; }

    public Nullable<long> PageButtonId { get; set; }

    public Nullable<double> Qty { get; set; }

    public Nullable<long> DAId { get; set; }



    public virtual PageButton PageButton { get; set; }

}

}
