
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PageButton
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PageButton()
    {

        this.PageButtonDetail = new HashSet<PageButtonDetail>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<short> PreparationTime { get; set; }

    public string ImageUri { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<short> Sort { get; set; }

    public Nullable<long> NavigateToPage { get; set; }

    public Nullable<long> SetDefaultPriceListId { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<long> PageId { get; set; }

    public string Color { get; set; }

    public string Background { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> SetDefaultSalesType { get; set; }

    public Nullable<bool> CanSavePrice { get; set; }

    public Nullable<long> DAId { get; set; }



    public virtual Pages Pages { get; set; }

    public virtual Product Product { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PageButtonDetail> PageButtonDetail { get; set; }

}

}
