
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Pages
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pages()
    {

        this.PageButton = new HashSet<PageButton>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string ExtendedDesc { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<short> Sort { get; set; }

    public Nullable<long> DefaultPriceList { get; set; }

    public Nullable<long> PageSetId { get; set; }

    public Nullable<long> DAId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PageButton> PageButton { get; set; }

    public virtual PageSet PageSet { get; set; }

}

}
