
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PayrollNew
{

    public long Id { get; set; }

    public string Identification { get; set; }

    public Nullable<System.DateTime> DateFrom { get; set; }

    public Nullable<System.DateTime> DateTo { get; set; }

    public long PosInfoId { get; set; }

    public long StaffId { get; set; }

    public string ShopId { get; set; }

    public string TotalHours { get; set; }

    public Nullable<short> IsSend { get; set; }

    public Nullable<long> TotalMinutes { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual PosInfo PosInfo { get; set; }

    public virtual Staff Staff { get; set; }

}

}
