
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PosInfoDetail_Excluded_Accounts
{

    public long Id { get; set; }

    public Nullable<long> PosInfoDetailId { get; set; }

    public Nullable<long> AccountId { get; set; }



    public virtual Accounts Accounts { get; set; }

    public virtual PosInfoDetail PosInfoDetail { get; set; }

}

}
