
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PosInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PosInfo()
    {

        this.ClientPos = new HashSet<ClientPos>();

        this.CreditTransactions = new HashSet<CreditTransactions>();

        this.EndOfDay = new HashSet<EndOfDay>();

        this.EODAccountToPmsTransfer = new HashSet<EODAccountToPmsTransfer>();

        this.Kds = new HashSet<Kds>();

        this.Lockers = new HashSet<Lockers>();

        this.MealConsumption = new HashSet<MealConsumption>();

        this.Notifications = new HashSet<Notifications>();

        this.Order = new HashSet<Order>();

        this.PagePosAssoc = new HashSet<PagePosAssoc>();

        this.Payrole = new HashSet<Payrole>();

        this.PayrollNew = new HashSet<PayrollNew>();

        this.PdaModule = new HashSet<PdaModule>();

        this.PosInfo_KitchenInstruction_Assoc = new HashSet<PosInfo_KitchenInstruction_Assoc>();

        this.PosInfo_Pricelist_Assoc = new HashSet<PosInfo_Pricelist_Assoc>();

        this.PosInfo_Region_Assoc = new HashSet<PosInfo_Region_Assoc>();

        this.PosInfo_StaffPositin_Assoc = new HashSet<PosInfo_StaffPositin_Assoc>();

        this.PosInfoDetail = new HashSet<PosInfoDetail>();

        this.PosInfoKdsAssoc = new HashSet<PosInfoKdsAssoc>();

        this.Region = new HashSet<Region>();

        this.RegionLockerProduct = new HashSet<RegionLockerProduct>();

        this.Transactions = new HashSet<Transactions>();

        this.Invoices = new HashSet<Invoices>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> FODay { get; set; }

    public Nullable<long> CloseId { get; set; }

    public string IPAddress { get; set; }

    public Nullable<byte> Type { get; set; }

    public string wsIP { get; set; }

    public string wsPort { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public string FiscalName { get; set; }

    public Nullable<byte> FiscalType { get; set; }

    public Nullable<bool> IsOpen { get; set; }

    public Nullable<long> ReceiptCount { get; set; }

    public Nullable<bool> ResetsReceiptCounter { get; set; }

    public string Theme { get; set; }

    public Nullable<long> AccountId { get; set; }

    public Nullable<bool> LogInToOrder { get; set; }

    public Nullable<bool> ClearTableManually { get; set; }

    public Nullable<bool> ViewOnly { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> InvoiceSumType { get; set; }

    public Nullable<short> LoginToOrderMode { get; set; }

    public Nullable<short> KeyboardType { get; set; }

    public string CustomerDisplayGif { get; set; }

    public Nullable<int> DefaultHotelId { get; set; }

    public string NfcDevice { get; set; }

    public string Configuration { get; set; }



    public virtual Accounts Accounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ClientPos> ClientPos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EndOfDay> EndOfDay { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EODAccountToPmsTransfer> EODAccountToPmsTransfer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kds> Kds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Lockers> Lockers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MealConsumption> MealConsumption { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notifications> Notifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Order { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PagePosAssoc> PagePosAssoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payrole> Payrole { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollNew> PayrollNew { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PdaModule> PdaModule { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_KitchenInstruction_Assoc> PosInfo_KitchenInstruction_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_Pricelist_Assoc> PosInfo_Pricelist_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_Region_Assoc> PosInfo_Region_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_StaffPositin_Assoc> PosInfo_StaffPositin_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfoDetail> PosInfoDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfoKdsAssoc> PosInfoKdsAssoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Region> Region { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RegionLockerProduct> RegionLockerProduct { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transactions> Transactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
