
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PosInfo_KitchenInstruction_Assoc
{

    public long Id { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> KitchenInstructionId { get; set; }



    public virtual KitchenInstruction KitchenInstruction { get; set; }

    public virtual PosInfo PosInfo { get; set; }

}

}
