

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PosEntities : DbContext
{
    public PosEntities()
        : base("name=PosEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Accounts> Accounts { get; set; }

    public virtual DbSet<Actions> Actions { get; set; }

    public virtual DbSet<AllowedMealsPerBoard> AllowedMealsPerBoard { get; set; }

    public virtual DbSet<AllowedMealsPerBoardDetails> AllowedMealsPerBoardDetails { get; set; }

    public virtual DbSet<AssignedPositions> AssignedPositions { get; set; }

    public virtual DbSet<AuthorizedGroup> AuthorizedGroup { get; set; }

    public virtual DbSet<AuthorizedGroupDetail> AuthorizedGroupDetail { get; set; }

    public virtual DbSet<BoardMeals> BoardMeals { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<ClientPos> ClientPos { get; set; }

    public virtual DbSet<Combo> Combo { get; set; }

    public virtual DbSet<ComboDetail> ComboDetail { get; set; }

    public virtual DbSet<CreditAccounts> CreditAccounts { get; set; }

    public virtual DbSet<CreditAccounts_Hist> CreditAccounts_Hist { get; set; }

    public virtual DbSet<CreditCodes> CreditCodes { get; set; }

    public virtual DbSet<CreditCodes_Hist> CreditCodes_Hist { get; set; }

    public virtual DbSet<CreditTransactions> CreditTransactions { get; set; }

    public virtual DbSet<CreditTransactions_Hist> CreditTransactions_Hist { get; set; }

    public virtual DbSet<DA_CustomerMessages> DA_CustomerMessages { get; set; }

    public virtual DbSet<DA_Customers> DA_Customers { get; set; }

    public virtual DbSet<DA_CustomersTokens> DA_CustomersTokens { get; set; }

    public virtual DbSet<DA_GeoPolygons> DA_GeoPolygons { get; set; }

    public virtual DbSet<DA_GeoPolygonsDetails> DA_GeoPolygonsDetails { get; set; }

    public virtual DbSet<DA_LoyalGainAmountRange> DA_LoyalGainAmountRange { get; set; }

    public virtual DbSet<DA_LoyalPoints> DA_LoyalPoints { get; set; }

    public virtual DbSet<DA_LoyalRedeemFreeProduct> DA_LoyalRedeemFreeProduct { get; set; }

    public virtual DbSet<DA_MainMessages> DA_MainMessages { get; set; }

    public virtual DbSet<DA_Messages> DA_Messages { get; set; }

    public virtual DbSet<DA_MessagesDetails> DA_MessagesDetails { get; set; }

    public virtual DbSet<DA_OrderDetails> DA_OrderDetails { get; set; }

    public virtual DbSet<DA_OrderDetailsExtras> DA_OrderDetailsExtras { get; set; }

    public virtual DbSet<DA_OrderStatus> DA_OrderStatus { get; set; }

    public virtual DbSet<DA_ScheduledTaskes> DA_ScheduledTaskes { get; set; }

    public virtual DbSet<DA_ShortageProds> DA_ShortageProds { get; set; }

    public virtual DbSet<DA_Stores> DA_Stores { get; set; }

    public virtual DbSet<DAStore_PriceListAssoc> DAStore_PriceListAssoc { get; set; }

    public virtual DbSet<Delivery_AddressTypes> Delivery_AddressTypes { get; set; }

    public virtual DbSet<Delivery_Customers> Delivery_Customers { get; set; }

    public virtual DbSet<Delivery_CustomersBillingAddress> Delivery_CustomersBillingAddress { get; set; }

    public virtual DbSet<Delivery_CustomersPhones> Delivery_CustomersPhones { get; set; }

    public virtual DbSet<Delivery_CustomersPhonesAndAddress> Delivery_CustomersPhonesAndAddress { get; set; }

    public virtual DbSet<Delivery_CustomersShippingAddress> Delivery_CustomersShippingAddress { get; set; }

    public virtual DbSet<Delivery_CustomersTypes> Delivery_CustomersTypes { get; set; }

    public virtual DbSet<Delivery_PhoneTypes> Delivery_PhoneTypes { get; set; }

    public virtual DbSet<Department> Department { get; set; }

    public virtual DbSet<DigitalSignature> DigitalSignature { get; set; }

    public virtual DbSet<Discount> Discount { get; set; }

    public virtual DbSet<EFoodBucket> EFoodBucket { get; set; }

    public virtual DbSet<EmailConfig> EmailConfig { get; set; }

    public virtual DbSet<EndOfDay> EndOfDay { get; set; }

    public virtual DbSet<EndOfDay_Hist> EndOfDay_Hist { get; set; }

    public virtual DbSet<EndOfDayDetail> EndOfDayDetail { get; set; }

    public virtual DbSet<EndOfDayDetail_Hist> EndOfDayDetail_Hist { get; set; }

    public virtual DbSet<EndOfDayPaymentAnalysis> EndOfDayPaymentAnalysis { get; set; }

    public virtual DbSet<EndOfDayPaymentAnalysis_Hist> EndOfDayPaymentAnalysis_Hist { get; set; }

    public virtual DbSet<EndOfDayVoidsAnalysis> EndOfDayVoidsAnalysis { get; set; }

    public virtual DbSet<EndOfDayVoidsAnalysis_Hist> EndOfDayVoidsAnalysis_Hist { get; set; }

    public virtual DbSet<EndOfYear> EndOfYear { get; set; }

    public virtual DbSet<EODAccountToPmsTransfer> EODAccountToPmsTransfer { get; set; }

    public virtual DbSet<EODAccountToPmsTransfer_Hist> EODAccountToPmsTransfer_Hist { get; set; }

    public virtual DbSet<ExternalLostOrders> ExternalLostOrders { get; set; }

    public virtual DbSet<ExternalLostOrders_Hist> ExternalLostOrders_Hist { get; set; }

    public virtual DbSet<ExternalProductMapping> ExternalProductMapping { get; set; }

    public virtual DbSet<ExternalStateMatch> ExternalStateMatch { get; set; }

    public virtual DbSet<ExternalUsers> ExternalUsers { get; set; }

    public virtual DbSet<ForexService> ForexService { get; set; }

    public virtual DbSet<Guest> Guest { get; set; }

    public virtual DbSet<GuestFuture> GuestFuture { get; set; }

    public virtual DbSet<HitPosCustomers> HitPosCustomers { get; set; }

    public virtual DbSet<HitPosOrders> HitPosOrders { get; set; }

    public virtual DbSet<HitPosOrders_Hist> HitPosOrders_Hist { get; set; }

    public virtual DbSet<HotelCustomerDataConfig> HotelCustomerDataConfig { get; set; }

    public virtual DbSet<HotelCustomMessages> HotelCustomMessages { get; set; }

    public virtual DbSet<HotelInfo> HotelInfo { get; set; }

    public virtual DbSet<HotelMacroResults> HotelMacroResults { get; set; }

    public virtual DbSet<HotelMacroRules> HotelMacroRules { get; set; }

    public virtual DbSet<HotelMacros> HotelMacros { get; set; }

    public virtual DbSet<HotelMacros_Hist> HotelMacros_Hist { get; set; }

    public virtual DbSet<HotelMacroTimezone> HotelMacroTimezone { get; set; }

    public virtual DbSet<Ingredient_ProdCategoryAssoc> Ingredient_ProdCategoryAssoc { get; set; }

    public virtual DbSet<IngredientCategories> IngredientCategories { get; set; }

    public virtual DbSet<Ingredients> Ingredients { get; set; }

    public virtual DbSet<Invoice_Guests_Trans> Invoice_Guests_Trans { get; set; }

    public virtual DbSet<Invoice_Guests_Trans_Hist> Invoice_Guests_Trans_Hist { get; set; }

    public virtual DbSet<InvoiceShippingDetails> InvoiceShippingDetails { get; set; }

    public virtual DbSet<InvoiceShippingDetails_Hist> InvoiceShippingDetails_Hist { get; set; }

    public virtual DbSet<InvoiceTypes> InvoiceTypes { get; set; }

    public virtual DbSet<Items> Items { get; set; }

    public virtual DbSet<Kds> Kds { get; set; }

    public virtual DbSet<Kitchen> Kitchen { get; set; }

    public virtual DbSet<KitchenInstruction> KitchenInstruction { get; set; }

    public virtual DbSet<KitchenInstruction_Hist> KitchenInstruction_Hist { get; set; }

    public virtual DbSet<KitchenInstructionLogger> KitchenInstructionLogger { get; set; }

    public virtual DbSet<KitchenInstructionLogger_Hist> KitchenInstructionLogger_Hist { get; set; }

    public virtual DbSet<KitchenRegion> KitchenRegion { get; set; }

    public virtual DbSet<Lockers> Lockers { get; set; }

    public virtual DbSet<Lockers_Hist> Lockers_Hist { get; set; }

    public virtual DbSet<Loyalty> Loyalty { get; set; }

    public virtual DbSet<Loyalty_Hist> Loyalty_Hist { get; set; }

    public virtual DbSet<MealConsumption> MealConsumption { get; set; }

    public virtual DbSet<MealConsumption_Hist> MealConsumption_Hist { get; set; }

    public virtual DbSet<MetadataTable> MetadataTable { get; set; }

    public virtual DbSet<NFCcard> NFCcard { get; set; }

    public virtual DbSet<Notifications> Notifications { get; set; }

    public virtual DbSet<OnlineRegistration> OnlineRegistration { get; set; }

    public virtual DbSet<OnlineRegistration_Hist> OnlineRegistration_Hist { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Order_Hist> Order_Hist { get; set; }

    public virtual DbSet<OrderDetail> OrderDetail { get; set; }

    public virtual DbSet<OrderDetail_Hist> OrderDetail_Hist { get; set; }

    public virtual DbSet<OrderDetailIgredients> OrderDetailIgredients { get; set; }

    public virtual DbSet<OrderDetailIgredients_Hist> OrderDetailIgredients_Hist { get; set; }

    public virtual DbSet<OrderDetailIgredientVatAnal> OrderDetailIgredientVatAnal { get; set; }

    public virtual DbSet<OrderDetailIgredientVatAnal_Hist> OrderDetailIgredientVatAnal_Hist { get; set; }

    public virtual DbSet<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    public virtual DbSet<OrderDetailInvoices_Hist> OrderDetailInvoices_Hist { get; set; }

    public virtual DbSet<OrderDetailVatAnal> OrderDetailVatAnal { get; set; }

    public virtual DbSet<OrderDetailVatAnal_Hist> OrderDetailVatAnal_Hist { get; set; }

    public virtual DbSet<OrdersStaff> OrdersStaff { get; set; }

    public virtual DbSet<OrdersStaff_Hist> OrdersStaff_Hist { get; set; }

    public virtual DbSet<OrderStatus> OrderStatus { get; set; }

    public virtual DbSet<OrderStatus_Hist> OrderStatus_Hist { get; set; }

    public virtual DbSet<PageButton> PageButton { get; set; }

    public virtual DbSet<PageButtonDetail> PageButtonDetail { get; set; }

    public virtual DbSet<PagePosAssoc> PagePosAssoc { get; set; }

    public virtual DbSet<Pages> Pages { get; set; }

    public virtual DbSet<PageSet> PageSet { get; set; }

    public virtual DbSet<Payrole> Payrole { get; set; }

    public virtual DbSet<PayrollNew> PayrollNew { get; set; }

    public virtual DbSet<PdaModule> PdaModule { get; set; }

    public virtual DbSet<PdaModuleDetail> PdaModuleDetail { get; set; }

    public virtual DbSet<PosInfo> PosInfo { get; set; }

    public virtual DbSet<PosInfo_KitchenInstruction_Assoc> PosInfo_KitchenInstruction_Assoc { get; set; }

    public virtual DbSet<PosInfo_Pricelist_Assoc> PosInfo_Pricelist_Assoc { get; set; }

    public virtual DbSet<PosInfo_Region_Assoc> PosInfo_Region_Assoc { get; set; }

    public virtual DbSet<PosInfo_StaffPositin_Assoc> PosInfo_StaffPositin_Assoc { get; set; }

    public virtual DbSet<PosInfoDetail> PosInfoDetail { get; set; }

    public virtual DbSet<PosInfoDetail_Excluded_Accounts> PosInfoDetail_Excluded_Accounts { get; set; }

    public virtual DbSet<PosInfoDetail_Pricelist_Assoc> PosInfoDetail_Pricelist_Assoc { get; set; }

    public virtual DbSet<PosInfoKdsAssoc> PosInfoKdsAssoc { get; set; }

    public virtual DbSet<PredefinedCredits> PredefinedCredits { get; set; }

    public virtual DbSet<Pricelist> Pricelist { get; set; }

    public virtual DbSet<PriceList_EffectiveHours> PriceList_EffectiveHours { get; set; }

    public virtual DbSet<PricelistDetail> PricelistDetail { get; set; }

    public virtual DbSet<PricelistMaster> PricelistMaster { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductBarcodes> ProductBarcodes { get; set; }

    public virtual DbSet<ProductCategories> ProductCategories { get; set; }

    public virtual DbSet<ProductExtras> ProductExtras { get; set; }

    public virtual DbSet<ProductForBarcodeEod> ProductForBarcodeEod { get; set; }

    public virtual DbSet<ProductRecipe> ProductRecipe { get; set; }

    public virtual DbSet<ProductSalesHistoryPerDay> ProductSalesHistoryPerDay { get; set; }

    public virtual DbSet<ProductsForEOD> ProductsForEOD { get; set; }

    public virtual DbSet<Promotions_Combos> Promotions_Combos { get; set; }

    public virtual DbSet<Promotions_Discounts> Promotions_Discounts { get; set; }

    public virtual DbSet<Promotions_Headers> Promotions_Headers { get; set; }

    public virtual DbSet<Promotions_Pricelists> Promotions_Pricelists { get; set; }

    public virtual DbSet<Region> Region { get; set; }

    public virtual DbSet<RegionLockerProduct> RegionLockerProduct { get; set; }

    public virtual DbSet<ReportEntity> ReportEntity { get; set; }

    public virtual DbSet<ReportList> ReportList { get; set; }

    public virtual DbSet<SalesType> SalesType { get; set; }

    public virtual DbSet<SalesType_PricelistMaster_Assoc> SalesType_PricelistMaster_Assoc { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<StaffAuthorization> StaffAuthorization { get; set; }

    public virtual DbSet<StaffCash> StaffCash { get; set; }

    public virtual DbSet<StaffPosition> StaffPosition { get; set; }

    public virtual DbSet<StaffSchedule> StaffSchedule { get; set; }

    public virtual DbSet<StaffSecheduleDetails> StaffSecheduleDetails { get; set; }

    public virtual DbSet<StatisticsMenus> StatisticsMenus { get; set; }

    public virtual DbSet<Store> Store { get; set; }

    public virtual DbSet<StoreMessages> StoreMessages { get; set; }

    public virtual DbSet<StoreMessages_Hist> StoreMessages_Hist { get; set; }

    public virtual DbSet<Suppliers> Suppliers { get; set; }

    public virtual DbSet<Table> Table { get; set; }

    public virtual DbSet<TablePaySuggestion> TablePaySuggestion { get; set; }

    public virtual DbSet<TablePaySuggestion_Hist> TablePaySuggestion_Hist { get; set; }

    public virtual DbSet<Tax> Tax { get; set; }

    public virtual DbSet<TR_Capacities> TR_Capacities { get; set; }

    public virtual DbSet<TR_Config> TR_Config { get; set; }

    public virtual DbSet<TR_ExcludeDays> TR_ExcludeDays { get; set; }

    public virtual DbSet<TR_ExcludeRestrictions> TR_ExcludeRestrictions { get; set; }

    public virtual DbSet<TR_OvewrittenCapacities> TR_OvewrittenCapacities { get; set; }

    public virtual DbSet<TR_ReservationCustomers> TR_ReservationCustomers { get; set; }

    public virtual DbSet<TR_Reservations> TR_Reservations { get; set; }

    public virtual DbSet<TR_Restaurants> TR_Restaurants { get; set; }

    public virtual DbSet<TR_Restrictions> TR_Restrictions { get; set; }

    public virtual DbSet<TR_Restrictions_Restaurants_Assoc> TR_Restrictions_Restaurants_Assoc { get; set; }

    public virtual DbSet<Transactions> Transactions { get; set; }

    public virtual DbSet<Transactions_Hist> Transactions_Hist { get; set; }

    public virtual DbSet<TransactionTypes> TransactionTypes { get; set; }

    public virtual DbSet<TransferMappingDetails> TransferMappingDetails { get; set; }

    public virtual DbSet<TransferMappingDetails_Hist> TransferMappingDetails_Hist { get; set; }

    public virtual DbSet<TransferMappings> TransferMappings { get; set; }

    public virtual DbSet<TransferMappings_Hist> TransferMappings_Hist { get; set; }

    public virtual DbSet<TransferToPms> TransferToPms { get; set; }

    public virtual DbSet<TransferToPms_Hist> TransferToPms_Hist { get; set; }

    public virtual DbSet<TransferToPms_LastIds> TransferToPms_LastIds { get; set; }

    public virtual DbSet<Units> Units { get; set; }

    public virtual DbSet<ValidModules> ValidModules { get; set; }

    public virtual DbSet<Vat> Vat { get; set; }

    public virtual DbSet<Version> Version { get; set; }

    public virtual DbSet<Vodafone11Details> Vodafone11Details { get; set; }

    public virtual DbSet<Vodafone11Headers> Vodafone11Headers { get; set; }

    public virtual DbSet<WorkSheet> WorkSheet { get; set; }

    public virtual DbSet<DA_LoyalConfig> DA_LoyalConfig { get; set; }

    public virtual DbSet<DA_LoyalGainAmountRatio> DA_LoyalGainAmountRatio { get; set; }

    public virtual DbSet<DA_LoyalRedeemDiscount> DA_LoyalRedeemDiscount { get; set; }

    public virtual DbSet<DA_Addresses> DA_Addresses { get; set; }

    public virtual DbSet<DA_Orders> DA_Orders { get; set; }

    public virtual DbSet<Invoices> Invoices { get; set; }

    public virtual DbSet<Invoices_Hist> Invoices_Hist { get; set; }

    public virtual DbSet<DeliveryRouting> DeliveryRouting { get; set; }

    public virtual DbSet<DeliveryRoutingHist> DeliveryRoutingHist { get; set; }

    public virtual DbSet<TR_ReservationTypes> TR_ReservationTypes { get; set; }


    public virtual int CancelReceipt(Nullable<long> invoiceId, Nullable<long> posInfo, Nullable<long> staffId, ObjectParameter newInvoiceId)
    {

        var invoiceIdParameter = invoiceId.HasValue ?
            new ObjectParameter("invoiceId", invoiceId) :
            new ObjectParameter("invoiceId", typeof(long));


        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CancelReceipt", invoiceIdParameter, posInfoParameter, staffIdParameter, newInvoiceId);
    }


    public virtual ObjectResult<EndOfDayAnalysisByAccount_Result> EndOfDayAnalysisByAccount(Nullable<long> posInfo, Nullable<long> staffId, Nullable<long> accountId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        var accountIdParameter = accountId.HasValue ?
            new ObjectParameter("AccountId", accountId) :
            new ObjectParameter("AccountId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisByAccount_Result>("EndOfDayAnalysisByAccount", posInfoParameter, staffIdParameter, accountIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisCanceled_Result> EndOfDayAnalysisCanceled(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisCanceled_Result>("EndOfDayAnalysisCanceled", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisDiscount_Result> EndOfDayAnalysisDiscount(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisDiscount_Result>("EndOfDayAnalysisDiscount", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisLoyaltyDiscount_Result> EndOfDayAnalysisLoyaltyDiscount(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisLoyaltyDiscount_Result>("EndOfDayAnalysisLoyaltyDiscount", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisNotInvoiced_Result> EndOfDayAnalysisNotInvoiced(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisNotInvoiced_Result>("EndOfDayAnalysisNotInvoiced", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisNotPaid_Result> EndOfDayAnalysisNotPaid(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisNotPaid_Result>("EndOfDayAnalysisNotPaid", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisNotPrinted_Result> EndOfDayAnalysisNotPrinted(Nullable<long> posInfo, Nullable<long> staffId)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisNotPrinted_Result>("EndOfDayAnalysisNotPrinted", posInfoParameter, staffIdParameter);
    }


    public virtual ObjectResult<EndOfDayAnalysisReceiptTotal_Result> EndOfDayAnalysisReceiptTotal(Nullable<long> posInfo, Nullable<long> staffId, Nullable<int> all)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        var allParameter = all.HasValue ?
            new ObjectParameter("All", all) :
            new ObjectParameter("All", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayAnalysisReceiptTotal_Result>("EndOfDayAnalysisReceiptTotal", posInfoParameter, staffIdParameter, allParameter);
    }


    public virtual ObjectResult<EndOfDayByStaff_Result> EndOfDayByStaff(Nullable<long> posInfo)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayByStaff_Result>("EndOfDayByStaff", posInfoParameter);
    }


    public virtual ObjectResult<EndOfDayTotal_Result> EndOfDayTotal(Nullable<long> posInfo, Nullable<int> bySalesType)
    {

        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var bySalesTypeParameter = bySalesType.HasValue ?
            new ObjectParameter("bySalesType", bySalesType) :
            new ObjectParameter("bySalesType", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EndOfDayTotal_Result>("EndOfDayTotal", posInfoParameter, bySalesTypeParameter);
    }


    public virtual ObjectResult<MoveDataToHistoric_Result> MoveDataToHistoric(Nullable<int> year)
    {

        var yearParameter = year.HasValue ?
            new ObjectParameter("Year", year) :
            new ObjectParameter("Year", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MoveDataToHistoric_Result>("MoveDataToHistoric", yearParameter);
    }


    public virtual int ReIndexAndShrink()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReIndexAndShrink");
    }


    public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));


        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }


    public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));


        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }


    public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
    }


    public virtual ObjectResult<sp_Execute_CloseOfYear_Result> sp_Execute_CloseOfYear(string sql, string jobname, string database, string owner)
    {

        var sqlParameter = sql != null ?
            new ObjectParameter("sql", sql) :
            new ObjectParameter("sql", typeof(string));


        var jobnameParameter = jobname != null ?
            new ObjectParameter("jobname", jobname) :
            new ObjectParameter("jobname", typeof(string));


        var databaseParameter = database != null ?
            new ObjectParameter("database", database) :
            new ObjectParameter("database", typeof(string));


        var ownerParameter = owner != null ?
            new ObjectParameter("owner", owner) :
            new ObjectParameter("owner", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Execute_CloseOfYear_Result>("sp_Execute_CloseOfYear", sqlParameter, jobnameParameter, databaseParameter, ownerParameter);
    }


    public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
    }


    public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
    }


    public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var new_diagramnameParameter = new_diagramname != null ?
            new ObjectParameter("new_diagramname", new_diagramname) :
            new ObjectParameter("new_diagramname", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
    }


    public virtual int sp_upgraddiagrams()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
    }


    public virtual int CancelOrder(Nullable<long> invoiceId, Nullable<long> posInfo, Nullable<long> staffId, ObjectParameter newInvoiceId)
    {

        var invoiceIdParameter = invoiceId.HasValue ?
            new ObjectParameter("invoiceId", invoiceId) :
            new ObjectParameter("invoiceId", typeof(long));


        var posInfoParameter = posInfo.HasValue ?
            new ObjectParameter("posInfo", posInfo) :
            new ObjectParameter("posInfo", typeof(long));


        var staffIdParameter = staffId.HasValue ?
            new ObjectParameter("staffId", staffId) :
            new ObjectParameter("staffId", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CancelOrder", invoiceIdParameter, posInfoParameter, staffIdParameter, newInvoiceId);
    }


    [DbFunction("PosEntities", "parseJSON")]
    public virtual IQueryable<parseJSON_Result> parseJSON(string jSON)
    {

        var jSONParameter = jSON != null ?
            new ObjectParameter("JSON", jSON) :
            new ObjectParameter("JSON", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<parseJSON_Result>("[PosEntities].[parseJSON](@JSON)", jSONParameter);
    }


    public virtual ObjectResult<SimplyStoreReport_Result> SimplyStoreReport(Nullable<int> fO_Month)
    {

        var fO_MonthParameter = fO_Month.HasValue ?
            new ObjectParameter("FO_Month", fO_Month) :
            new ObjectParameter("FO_Month", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SimplyStoreReport_Result>("SimplyStoreReport", fO_MonthParameter);
    }


    public virtual ObjectResult<TR_GetAvailableRestaurantsDatesAndTime_Result> TR_GetAvailableRestaurantsDatesAndTime(string totProfiles, string totRooms, Nullable<int> paxes, Nullable<int> dur, string sLang, Nullable<int> restId, Nullable<System.DateTime> activeDate)
    {

        var totProfilesParameter = totProfiles != null ?
            new ObjectParameter("TotProfiles", totProfiles) :
            new ObjectParameter("TotProfiles", typeof(string));


        var totRoomsParameter = totRooms != null ?
            new ObjectParameter("TotRooms", totRooms) :
            new ObjectParameter("TotRooms", typeof(string));


        var paxesParameter = paxes.HasValue ?
            new ObjectParameter("Paxes", paxes) :
            new ObjectParameter("Paxes", typeof(int));


        var durParameter = dur.HasValue ?
            new ObjectParameter("dur", dur) :
            new ObjectParameter("dur", typeof(int));


        var sLangParameter = sLang != null ?
            new ObjectParameter("sLang", sLang) :
            new ObjectParameter("sLang", typeof(string));


        var restIdParameter = restId.HasValue ?
            new ObjectParameter("RestId", restId) :
            new ObjectParameter("RestId", typeof(int));


        var activeDateParameter = activeDate.HasValue ?
            new ObjectParameter("ActiveDate", activeDate) :
            new ObjectParameter("ActiveDate", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TR_GetAvailableRestaurantsDatesAndTime_Result>("TR_GetAvailableRestaurantsDatesAndTime", totProfilesParameter, totRoomsParameter, paxesParameter, durParameter, sLangParameter, restIdParameter, activeDateParameter);
    }

}

}

