
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PredefinedCredits
{

    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<long> InvoiceTypeId { get; set; }



    public virtual InvoiceTypes InvoiceTypes { get; set; }

}

}
