
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PricelistDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PricelistDetail()
    {

        this.OrderDetail = new HashSet<OrderDetail>();

        this.OrderDetailIgredients = new HashSet<OrderDetailIgredients>();

    }


    public long Id { get; set; }

    public Nullable<long> PricelistId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> VatId { get; set; }

    public Nullable<long> TaxId { get; set; }

    public Nullable<long> IngredientId { get; set; }

    public Nullable<decimal> PriceWithout { get; set; }

    public Nullable<int> MinRequiredExtras { get; set; }

    public Nullable<long> DAId { get; set; }



    public virtual Ingredients Ingredients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailIgredients> OrderDetailIgredients { get; set; }

    public virtual Pricelist Pricelist { get; set; }

    public virtual Product Product { get; set; }

    public virtual Tax Tax { get; set; }

    public virtual Vat Vat { get; set; }

}

}
