
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class PriceList_EffectiveHours
{

    public long Id { get; set; }

    public Nullable<long> PricelistId { get; set; }

    public Nullable<System.DateTime> FromTime { get; set; }

    public Nullable<System.DateTime> ToTime { get; set; }

    public Nullable<long> DAId { get; set; }



    public virtual Pricelist Pricelist { get; set; }

}

}
