
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Pricelist
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pricelist()
    {

        this.AllowedMealsPerBoard = new HashSet<AllowedMealsPerBoard>();

        this.DAStore_PriceListAssoc = new HashSet<DAStore_PriceListAssoc>();

        this.OrderDetailInvoices = new HashSet<OrderDetailInvoices>();

        this.PosInfo_Pricelist_Assoc = new HashSet<PosInfo_Pricelist_Assoc>();

        this.PosInfoDetail_Pricelist_Assoc = new HashSet<PosInfoDetail_Pricelist_Assoc>();

        this.PriceList_EffectiveHours = new HashSet<PriceList_EffectiveHours>();

        this.PricelistDetail = new HashSet<PricelistDetail>();

        this.Promotions_Pricelists = new HashSet<Promotions_Pricelists>();

        this.RegionLockerProduct = new HashSet<RegionLockerProduct>();

        this.TransferMappings = new HashSet<TransferMappings>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public Nullable<long> LookUpPriceListId { get; set; }

    public Nullable<double> Percentage { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<System.DateTime> ActivationDate { get; set; }

    public Nullable<System.DateTime> DeactivationDate { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<long> PricelistMasterId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<short> Type { get; set; }

    public Nullable<long> DAId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AllowedMealsPerBoard> AllowedMealsPerBoard { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DAStore_PriceListAssoc> DAStore_PriceListAssoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfo_Pricelist_Assoc> PosInfo_Pricelist_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PosInfoDetail_Pricelist_Assoc> PosInfoDetail_Pricelist_Assoc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PriceList_EffectiveHours> PriceList_EffectiveHours { get; set; }

    public virtual PricelistMaster PricelistMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PricelistDetail> PricelistDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Promotions_Pricelists> Promotions_Pricelists { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RegionLockerProduct> RegionLockerProduct { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferMappings> TransferMappings { get; set; }

}

}
