
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ProductSalesHistoryPerDay
{

    public long Id { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> ProductCategoryId { get; set; }

    public Nullable<long> CategoryId { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<long> InvoiceTypeId { get; set; }

    public Nullable<long> VatId { get; set; }

    public Nullable<long> EodId { get; set; }

    public string ProductDescription { get; set; }

    public string PosInfoDescription { get; set; }

    public string DepartmentDescription { get; set; }

    public string ProductCategoryDescription { get; set; }

    public string CategoryDescription { get; set; }

    public string SalesTypeDescription { get; set; }

    public string PriceListDescription { get; set; }

    public string InvoiceTypeDescription { get; set; }

    public string StaffName { get; set; }

    public string ProductCode { get; set; }

    public string PriceListCode { get; set; }

    public Nullable<bool> IsVoided { get; set; }

    public Nullable<int> Covers { get; set; }

    public Nullable<decimal> Qty { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<decimal> VatAmount { get; set; }

    public Nullable<decimal> Net { get; set; }

    public Nullable<decimal> VatRate { get; set; }

    public Nullable<int> InvoiceCount { get; set; }

    public Nullable<decimal> UnitPrice { get; set; }

}

}
