
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ProductExtras
{

    public long Id { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<bool> IsRequired { get; set; }

    public Nullable<long> IngredientId { get; set; }

    public Nullable<double> MinQty { get; set; }

    public Nullable<double> MaxQty { get; set; }

    public Nullable<long> UnitId { get; set; }

    public Nullable<long> ItemsId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<long> ProductAsIngridientId { get; set; }

    public Nullable<int> Sort { get; set; }

    public Nullable<long> DAId { get; set; }

    public Nullable<bool> CanSavePrice { get; set; }



    public virtual Ingredients Ingredients { get; set; }

    public virtual Items Items { get; set; }

    public virtual Product Product { get; set; }

    public virtual Units Units { get; set; }

}

}
