
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ProductCategories
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductCategories()
    {

        this.AllowedMealsPerBoardDetails = new HashSet<AllowedMealsPerBoardDetails>();

        this.DA_LoyalRedeemFreeProduct = new HashSet<DA_LoyalRedeemFreeProduct>();

        this.Product = new HashSet<Product>();

        this.TransferMappings = new HashSet<TransferMappings>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<byte> Status { get; set; }

    public string Code { get; set; }

    public Nullable<long> CategoryId { get; set; }

    public Nullable<long> DAId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AllowedMealsPerBoardDetails> AllowedMealsPerBoardDetails { get; set; }

    public virtual Categories Categories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_LoyalRedeemFreeProduct> DA_LoyalRedeemFreeProduct { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Product { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferMappings> TransferMappings { get; set; }

}

}
