
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Promotions_Combos
{

    public long Id { get; set; }

    public Nullable<long> HeaderId { get; set; }

    public Nullable<long> ItemId { get; set; }

    public Nullable<decimal> ItemQuantity { get; set; }

    public Nullable<bool> ItemIsProduct { get; set; }

    public Nullable<long> DAId { get; set; }



    public virtual Promotions_Headers Promotions_Headers { get; set; }

}

}
