
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Promotions_Headers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Promotions_Headers()
    {

        this.Promotions_Combos = new HashSet<Promotions_Combos>();

        this.Promotions_Discounts = new HashSet<Promotions_Discounts>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string Code { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<bool> AskOperator { get; set; }

    public string ReceiptNote { get; set; }

    public Nullable<int> DiscountType { get; set; }

    public Nullable<bool> AskCode { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<long> DAId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Promotions_Combos> Promotions_Combos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Promotions_Discounts> Promotions_Discounts { get; set; }

}

}
