
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class RegionLockerProduct
{

    public long Id { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public string SalesDescription { get; set; }

    public Nullable<long> ReturnPaymentpId { get; set; }

    public Nullable<long> PaymentId { get; set; }

    public Nullable<long> SaleId { get; set; }

    public Nullable<long> PosInfoId { get; set; }



    public virtual PosInfo PosInfo { get; set; }

    public virtual Pricelist Pricelist { get; set; }

    public virtual Product Product { get; set; }

}

}
