
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class SalesType_PricelistMaster_Assoc
{

    public long Id { get; set; }

    public Nullable<long> PricelistMasterId { get; set; }

    public Nullable<long> SalesTypeId { get; set; }



    public virtual PricelistMaster PricelistMaster { get; set; }

    public virtual SalesType SalesType { get; set; }

}

}
