
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class StaffSchedule
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StaffSchedule()
    {

        this.StaffSecheduleDetails = new HashSet<StaffSecheduleDetails>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> Day { get; set; }

    public Nullable<long> DepartmentId { get; set; }



    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffSecheduleDetails> StaffSecheduleDetails { get; set; }

}

}
