
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class StaffSecheduleDetails
{

    public long Id { get; set; }

    public Nullable<long> StaffSceduleId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<long> StaffPositionId { get; set; }

    public Nullable<System.DateTime> Hour { get; set; }



    public virtual Staff Staff { get; set; }

    public virtual StaffSchedule StaffSchedule { get; set; }

}

}
