
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class StaffCash
{

    public long Id { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<decimal> CashAmount { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<System.DateTime> Date { get; set; }



    public virtual EndOfDay EndOfDay { get; set; }

    public virtual Staff Staff { get; set; }

}

}
