
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Staff
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Staff()
    {

        this.AssignedPositions = new HashSet<AssignedPositions>();

        this.CreditTransactions = new HashSet<CreditTransactions>();

        this.DA_LoyalPoints = new HashSet<DA_LoyalPoints>();

        this.MealConsumption = new HashSet<MealConsumption>();

        this.Order = new HashSet<Order>();

        this.OrderDetailInvoices = new HashSet<OrderDetailInvoices>();

        this.OrdersStaff = new HashSet<OrdersStaff>();

        this.OrderStatus = new HashSet<OrderStatus>();

        this.Payrole = new HashSet<Payrole>();

        this.PayrollNew = new HashSet<PayrollNew>();

        this.StaffAuthorization = new HashSet<StaffAuthorization>();

        this.StaffCash = new HashSet<StaffCash>();

        this.StaffSecheduleDetails = new HashSet<StaffSecheduleDetails>();

        this.Transactions = new HashSet<Transactions>();

        this.WorkSheet = new HashSet<WorkSheet>();

        this.Invoices = new HashSet<Invoices>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ImageUri { get; set; }

    public string Password { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string Identification { get; set; }

    public Nullable<long> DASTORE { get; set; }

    public Nullable<bool> IsOnRoad { get; set; }

    public Nullable<System.DateTime> StatusTimeChanged { get; set; }

    public Nullable<bool> isAdmin { get; set; }

    public Nullable<bool> LogInAfterOrder { get; set; }

    public Nullable<bool> AllowReporting { get; set; }

    public Nullable<bool> isAssignedToRoute { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssignedPositions> AssignedPositions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DA_LoyalPoints> DA_LoyalPoints { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MealConsumption> MealConsumption { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Order { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetailInvoices> OrderDetailInvoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdersStaff> OrdersStaff { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderStatus> OrderStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Payrole> Payrole { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollNew> PayrollNew { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffAuthorization> StaffAuthorization { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffCash> StaffCash { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffSecheduleDetails> StaffSecheduleDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transactions> Transactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkSheet> WorkSheet { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
