
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class StatisticsMenus
{

    public long Id { get; set; }

    public string MenuDescription { get; set; }

    public Nullable<short> CategoryOrder { get; set; }

    public string MenuItemDescription { get; set; }

    public Nullable<short> MenuItemOrder { get; set; }

    public Nullable<short> MenuLevel { get; set; }

    public Nullable<long> ReportListId { get; set; }

    public Nullable<long> ParentMenuId { get; set; }

    public string Url { get; set; }



    public virtual ReportList ReportList { get; set; }

}

}
