
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Store
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Store()
    {

        this.HotelInfo = new HashSet<HotelInfo>();

        this.Notifications = new HashSet<Notifications>();

        this.StoreMessages = new HashSet<StoreMessages>();

    }


    public long Id { get; set; }

    public string Description { get; set; }

    public string ExtDescription { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Phone3 { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Latitude { get; set; }

    public string Longtitude { get; set; }

    public string ImageUri { get; set; }

    public string LogoUri { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<System.Guid> StoreMapId { get; set; }

    public Nullable<short> StoreKitchenInstruction { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HotelInfo> HotelInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notifications> Notifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StoreMessages> StoreMessages { get; set; }

}

}
