
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class StoreMessages_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public string Message { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string Title { get; set; }

    public Nullable<long> StoreId { get; set; }

    public Nullable<System.DateTime> ShowFrom { get; set; }

    public Nullable<System.DateTime> ShowTo { get; set; }

    public string ImageUri { get; set; }

    public Nullable<byte> Status { get; set; }

}

}
