
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TablePaySuggestion
{

    public long Id { get; set; }

    public Nullable<long> AccountId { get; set; }

    public Nullable<long> GuestId { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<long> OrderDetailId { get; set; }

    public Nullable<bool> IsUsed { get; set; }

    public Nullable<long> CreditCodeId { get; set; }



    public virtual Accounts Accounts { get; set; }

    public virtual CreditCodes CreditCodes { get; set; }

    public virtual Guest Guest { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

}

}
