
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Table
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Table()
    {

        this.OrderDetail = new HashSet<OrderDetail>();

        this.Invoices = new HashSet<Invoices>();

    }


    public long Id { get; set; }

    public string Code { get; set; }

    public string SalesDescription { get; set; }

    public string Description { get; set; }

    public Nullable<int> MinCapacity { get; set; }

    public Nullable<int> MaxCapacity { get; set; }

    public Nullable<long> RegionId { get; set; }

    public Nullable<byte> Status { get; set; }

    public string YPos { get; set; }

    public string XPos { get; set; }

    public Nullable<bool> IsOnline { get; set; }

    public Nullable<short> ReservationStatus { get; set; }

    public Nullable<long> Shape { get; set; }

    public Nullable<int> TurnoverTime { get; set; }

    public string ImageUri { get; set; }

    public Nullable<double> Width { get; set; }

    public Nullable<double> Height { get; set; }

    public string Angle { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

    public virtual Region Region { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoices> Invoices { get; set; }

}

}
