
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TR_Capacities
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TR_Capacities()
    {

        this.TR_OvewrittenCapacities = new HashSet<TR_OvewrittenCapacities>();

        this.TR_Reservations = new HashSet<TR_Reservations>();

    }


    public long Id { get; set; }

    public long RestId { get; set; }

    public int Capacity { get; set; }

    public int Type { get; set; }

    public System.TimeSpan Time { get; set; }



    public virtual TR_Restaurants TR_Restaurants { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_OvewrittenCapacities> TR_OvewrittenCapacities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_Reservations> TR_Reservations { get; set; }

}

}
