
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TR_Restrictions_Restaurants_Assoc
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TR_Restrictions_Restaurants_Assoc()
    {

        this.TR_ExcludeRestrictions = new HashSet<TR_ExcludeRestrictions>();

    }


    public long Id { get; set; }

    public long RestrictId { get; set; }

    public long RestId { get; set; }

    public int N { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_ExcludeRestrictions> TR_ExcludeRestrictions { get; set; }

    public virtual TR_Restaurants TR_Restaurants { get; set; }

    public virtual TR_Restrictions TR_Restrictions { get; set; }

}

}
