
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TR_Restaurants
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TR_Restaurants()
    {

        this.TR_Capacities = new HashSet<TR_Capacities>();

        this.TR_ExcludeDays = new HashSet<TR_ExcludeDays>();

        this.TR_ExcludeRestrictions = new HashSet<TR_ExcludeRestrictions>();

        this.TR_OvewrittenCapacities = new HashSet<TR_OvewrittenCapacities>();

        this.TR_Restrictions_Restaurants_Assoc = new HashSet<TR_Restrictions_Restaurants_Assoc>();

    }


    public long Id { get; set; }

    public string NameGR { get; set; }

    public string NameEn { get; set; }

    public string NameRu { get; set; }

    public string NameFr { get; set; }

    public string NameDe { get; set; }

    public string Image { get; set; }

    public string DescriptionGR { get; set; }

    public string DescriptionEn { get; set; }

    public string DescriptionRu { get; set; }

    public string DescriptionFr { get; set; }

    public string DescriptionDe { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_Capacities> TR_Capacities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_ExcludeDays> TR_ExcludeDays { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_ExcludeRestrictions> TR_ExcludeRestrictions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_OvewrittenCapacities> TR_OvewrittenCapacities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TR_Restrictions_Restaurants_Assoc> TR_Restrictions_Restaurants_Assoc { get; set; }

}

}
