
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TransferToPms_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public string RegNo { get; set; }

    public string PmsDepartmentId { get; set; }

    public string Description { get; set; }

    public string ProfileId { get; set; }

    public string ProfileName { get; set; }

    public Nullable<long> TransactionId { get; set; }

    public Nullable<short> TransferType { get; set; }

    public string RoomId { get; set; }

    public string RoomDescription { get; set; }

    public string ReceiptNo { get; set; }

    public Nullable<long> PosInfoDetailId { get; set; }

    public Nullable<bool> SendToPMS { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<System.DateTime> SendToPmsTS { get; set; }

    public string ErrorMessage { get; set; }

    public string PmsResponseId { get; set; }

    public Nullable<System.Guid> TransferIdentifier { get; set; }

    public string PmsDepartmentDescription { get; set; }

    public Nullable<short> Status { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public Nullable<long> HotelId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> Points { get; set; }

    public Nullable<long> PMSPaymentId { get; set; }

    public Nullable<long> PMSInvoiceId { get; set; }

    public Nullable<long> InvoiceId { get; set; }

    public byte[] HtmlReceipt { get; set; }

}

}
