
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TransferMappings
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TransferMappings()
    {

        this.TransferMappingDetails = new HashSet<TransferMappingDetails>();

    }


    public long Id { get; set; }

    public string PmsDepartmentId { get; set; }

    public string PmsDepDescription { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<double> VatPercentage { get; set; }

    public Nullable<long> PosDepartmentId { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<int> VatCode { get; set; }

    public Nullable<long> ProductCategoryId { get; set; }

    public Nullable<long> HotelId { get; set; }



    public virtual Department Department { get; set; }

    public virtual Pricelist Pricelist { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductCategories ProductCategories { get; set; }

    public virtual SalesType SalesType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferMappingDetails> TransferMappingDetails { get; set; }

}

}
