
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class TransferMappings_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public string PmsDepartmentId { get; set; }

    public string PmsDepDescription { get; set; }

    public Nullable<long> ProductId { get; set; }

    public Nullable<long> SalesTypeId { get; set; }

    public Nullable<double> VatPercentage { get; set; }

    public Nullable<long> PosDepartmentId { get; set; }

    public Nullable<long> PriceListId { get; set; }

    public Nullable<int> VatCode { get; set; }

    public Nullable<long> ProductCategoryId { get; set; }

    public Nullable<long> HotelId { get; set; }

}

}
