
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Transactions_Hist
{

    public int nYear { get; set; }

    public long Id { get; set; }

    public Nullable<System.DateTime> Day { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<long> OrderId { get; set; }

    public Nullable<short> TransactionType { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public string Description { get; set; }

    public Nullable<long> AccountId { get; set; }

    public Nullable<short> InOut { get; set; }

    public Nullable<decimal> Gross { get; set; }

    public Nullable<decimal> Net { get; set; }

    public Nullable<decimal> Vat { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public string ExtDescription { get; set; }

    public Nullable<long> InvoicesId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<long> SupplierId { get; set; }

}

}
