
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class Transactions
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transactions()
    {

        this.CreditTransactions = new HashSet<CreditTransactions>();

        this.Invoice_Guests_Trans = new HashSet<Invoice_Guests_Trans>();

        this.OrderDetail = new HashSet<OrderDetail>();

        this.TransferToPms = new HashSet<TransferToPms>();

    }


    public long Id { get; set; }

    public Nullable<System.DateTime> Day { get; set; }

    public Nullable<long> PosInfoId { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<long> OrderId { get; set; }

    public Nullable<short> TransactionType { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<long> DepartmentId { get; set; }

    public string Description { get; set; }

    public Nullable<long> AccountId { get; set; }

    public Nullable<short> InOut { get; set; }

    public Nullable<decimal> Gross { get; set; }

    public Nullable<decimal> Net { get; set; }

    public Nullable<decimal> Vat { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public Nullable<long> EndOfDayId { get; set; }

    public string ExtDescription { get; set; }

    public Nullable<long> InvoicesId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<long> SupplierId { get; set; }



    public virtual Accounts Accounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditTransactions> CreditTransactions { get; set; }

    public virtual Department Department { get; set; }

    public virtual EndOfDay EndOfDay { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Invoice_Guests_Trans> Invoice_Guests_Trans { get; set; }

    public virtual Order Order { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

    public virtual PosInfo PosInfo { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Suppliers Suppliers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransferToPms> TransferToPms { get; set; }

    public virtual Invoices Invoices { get; set; }

}

}
