
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class ValidModules
{

    public long Id { get; set; }

    public Nullable<short> ModuleType { get; set; }

    public Nullable<int> MaxInstances { get; set; }

}

}
