
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pos_WebApi
{

using System;
    using System.Collections.Generic;
    
public partial class WorkSheet
{

    public long Id { get; set; }

    public Nullable<long> StaffId { get; set; }

    public Nullable<System.DateTime> Day { get; set; }

    public Nullable<System.DateTime> Hour { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<long> DepartmentId { get; set; }



    public virtual Department Department { get; set; }

    public virtual Staff Staff { get; set; }

}

}
