using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Symposium_DTOs.PosModel_Info
{
    [DisplayName("Ver : 2.0.0.8")]
    public class Version_2_0_0_8
    {
        public List<string> Ver_2_0_0_8 { get; }

        public Version_2_0_0_8()
        {
            Ver_2_0_0_8 = new List<string>();
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisReceiptTotal] @posInfo BIGINT, @staffId BIGINT, @All INT AS  \n"
                           + "BEGIN  \n"
                           + "	/* \n"
                           + "	 * @All \n"
                           + "	 * 0	Splitted invoices will viewed as one row (Total from Invoice [Total]) \n"
                           + "	 * 1	Splitted invoices will viewed with all rows (Total from Transaction [Amount]) \n"
                           + "	 */ \n"
                           + "	/*Gets a list of all printed and not voieded invoices */ \n"
                           + "	 \n"
                           + "	IF @All = 0 \n"
                           + "		SELECT res.* \n"
                           + "		FROM ( \n"
                           + "			SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                           + "			FROM ( \n"
                           + "				SELECT  \n"
                           + "					i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,3,8,10) \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				CROSS APPLY( \n"
                           + "					SELECT TOP 1 t.InvoicesId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "					FROM Transactions AS t	 \n"
                           + "					WHERE t.EndOfDayId IS NULL AND t.PosInfoId = @posInfo AND ISNULL(t.IsDeleted,0) <> 1 AND  \n"
                           + "						((NOT (t.TransactionType = 9 AND t.InOut = 1))) AND t.TransactionType NOT IN (8,7)	AND  \n"
                           + "						t.InvoicesId = i.Id \n"
                           + "				) t \n"
                           + "				WHERE ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPaid,0) <> 1   \n"
                           + "				 \n"
                           + "			 \n"
                           + "				UNION ALL \n"
                           + "				SELECT i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId  AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				LEFT OUTER JOIN Transactions AS t ON t.InvoicesId = i.Id \n"
                           + "				WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 \n"
                           + "				 AND t.InvoicesId IS NULL \n"
                           + "			 \n"
                           + "				UNION ALL \n"
                           + "				SELECT i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId  AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				OUTER APPLY( \n"
                           + "					SELECT TOP 1 t.InvoicesId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "					FROM Transactions AS t	 \n"
                           + "					WHERE t.EndOfDayId IS NULL AND t.PosInfoId = @posInfo AND ISNULL(t.IsDeleted,0) <> 1 AND  \n"
                           + "						((NOT (t.TransactionType = 9 AND t.InOut = 1))) AND t.TransactionType NOT IN (8,7)	AND  \n"
                           + "						t.InvoicesId = i.Id \n"
                           + "				) t \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND ISNULL(i.IsPaid,0) = 1 \n"
                           + "			) fin \n"
                           + "		) res \n"
                           + "		ORDER BY res.Id \n"
                           + "	ELSE \n"
                           + "		SELECT res.* \n"
                           + "		FROM ( \n"
                           + "			SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                           + "			FROM ( \n"
                           + "				SELECT  \n"
                           + "					i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(t.Amount) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,3,8,10) \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				CROSS APPLY( \n"
                           + "					SELECT t.InvoicesId, ISNULL(t.AccountId,0) AccountId, t.Amount  \n"
                           + "					FROM Transactions AS t	 \n"
                           + "					WHERE t.EndOfDayId IS NULL AND t.PosInfoId = @posInfo AND ISNULL(t.IsDeleted,0) <> 1 AND  \n"
                           + "						((NOT (t.TransactionType = 9 AND t.InOut = 1))) AND t.TransactionType NOT IN (8,7)	AND  \n"
                           + "						t.InvoicesId = i.Id \n"
                           + "				) t \n"
                           + "				WHERE ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPaid,0) <> 1  \n"
                           + "				 \n"
                           + "			 \n"
                           + "				UNION ALL \n"
                           + "				SELECT i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId  \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId  AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				LEFT OUTER JOIN Transactions AS t ON t.InvoicesId = i.Id \n"
                           + "				WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 \n"
                           + "				 AND t.InvoicesId IS NULL \n"
                           + "			 \n"
                           + "				UNION ALL \n"
                           + "				SELECT i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "					it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "					(t.Amount) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "					odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "					ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "					ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId, ISNULL(t.AccountId,0) AccountId \n"
                           + "				FROM Invoices AS i \n"
                           + "				INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId  AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "				INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "					CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "				INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "				INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "				LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "				OUTER APPLY( \n"
                           + "					SELECT t.InvoicesId, ISNULL(t.AccountId,0) AccountId, t.Amount  \n"
                           + "					FROM Transactions AS t	 \n"
                           + "					WHERE t.EndOfDayId IS NULL AND t.PosInfoId = @posInfo AND ISNULL(t.IsDeleted,0) <> 1 AND  \n"
                           + "						((NOT (t.TransactionType = 9 AND t.InOut = 1))) AND t.TransactionType NOT IN (8,7)	AND  \n"
                           + "						t.InvoicesId = i.Id \n"
                           + "				) t \n"
                           + "				CROSS APPLY ( \n"
                           + "					SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "					FROM OrderDetailInvoices AS odi \n"
                           + "					OUTER APPLY ( \n"
                           + "						SELECT odg.Id  \n"
                           + "						FROM OrderDetailIgredients AS odg \n"
                           + "						WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "					) odg \n"
                           + "					WHERE odi.InvoicesId = i.Id \n"
                           + "				)odi \n"
                           + "				WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND ISNULL(i.IsPaid,0) = 1 \n"
                           + "			) fin \n"
                           + "		) res \n"
                           + "		ORDER BY res.Id \n"
                           + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisByAccount] @posInfo BIGINT, @staffId BIGINT, @AccountId BIGINT AS \n"
                           + "BEGIN  \n"
                           + "	/*Gets a list of invoices for a specific account ID (Cash, Credit Cards, Coplimentary each...)*/ \n"
                           + "	SELECT res.* \n"
                           + "	FROM ( \n"
                           + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) ID, fin.* \n"
                           + "		FROM ( \n"
                           + "			SELECT  \n"
                           + "				i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "				it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "				ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN Transactions AS t ON i.Id = t.InvoicesId AND t.PosInfoId = i.PosInfoId AND \n"
                           + "				t.EndOfDayId IS NULL AND ISNULL(t.IsDeleted,0) <> 1 AND  \n"
                           + "				((NOT (t.TransactionType = 9 AND t.InOut = 1))) AND t.TransactionType NOT IN (8,7) AND t.AccountId = @AccountId \n"
                           + "			INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "			INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,3,8,9) \n"
                           + "			LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "			INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "				CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "			CROSS APPLY ( \n"
                           + "				SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "				FROM OrderDetailInvoices AS odi \n"
                           + "				OUTER APPLY ( \n"
                           + "					SELECT odg.Id  \n"
                           + "					FROM OrderDetailIgredients AS odg \n"
                           + "					WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "				) odg \n"
                           + "				WHERE odi.InvoicesId = i.Id \n"
                           + "			)odi \n"
                           + "			WHERE i.EndOfDayId IS NULL AND i.PosInfoId = @posInfo AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 \n"
                           + "		) fin \n"
                           + "	) res \n"
                           + "	ORDER BY res.ID \n"
                           + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisCanceled] @posInfo BIGINT, @staffId BIGINT AS  \n"
                            + "BEGIN  \n"
                            + "	/*Gets a list of canceld invoices*/ \n"
                            + "	SELECT res.* \n"
                            + "	FROM ( \n"
                            + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                            + "		FROM ( \n"
                            + "			SELECT  \n"
                            + "				i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                            + "				it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                            + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                            + "				odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                            + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                            + "				ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId  \n"
                            + "			FROM Invoices AS i \n"
                            + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] IN (3) \n"
                            + "			INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                            + "			INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                            + "			LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                            + "			INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                            + "				CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                            + "			CROSS APPLY ( \n"
                            + "				SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                            + "				FROM OrderDetailInvoices AS odi \n"
                            + "				OUTER APPLY ( \n"
                            + "					SELECT odg.Id  \n"
                            + "					FROM OrderDetailIgredients AS odg \n"
                            + "					WHERE odg.OrderDetailId = odi.Id	 \n"
                            + "				) odg \n"
                            + "				WHERE odi.InvoicesId = i.Id \n"
                            + "			)odi \n"
                            + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 1 \n"
                            + "		) fin \n"
                            + "	) res \n"
                            + "	ORDER BY res.Id \n"
                            + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisDiscount] @posInfo BIGINT, @staffId BIGINT AS  \n"
                           + "BEGIN  \n"
                           + "	/*Gets a list of invoices with Discount*/ \n"
                           + "	SELECT res.* \n"
                           + "	FROM ( \n"
                           + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                           + "		FROM ( \n"
                           + "			SELECT  \n"
                           + "				i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "				it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "				ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,8,10,11,12) \n"
                           + "			INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "			INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "			LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "			INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "				CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "			CROSS APPLY ( \n"
                           + "				SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "				FROM OrderDetailInvoices AS odi \n"
                           + "				OUTER APPLY ( \n"
                           + "					SELECT odg.Id  \n"
                           + "					FROM OrderDetailIgredients AS odg \n"
                           + "					WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "				) odg \n"
                           + "				WHERE odi.InvoicesId = i.Id \n"
                           + "			)odi \n"
                           + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND  \n"
                           + "				ISNULL(i.Discount,0) <> 0 \n"
                           + "		) fin \n"
                           + "	) res \n"
                           + "	ORDER BY res.Id \n"
                           + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisNotInvoiced] @posInfo BIGINT, @staffId BIGINT AS  \n"
                           + "BEGIN  \n"
                           + "	/*Gets a list of not invoiced invoices*/ \n"
                           + "	SELECT res.* \n"
                           + "	FROM ( \n"
                           + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                           + "		FROM ( \n"
                           + "			SELECT  \n"
                           + "				i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "				it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "				ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] IN (2,8) \n"
                           + "			INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "			INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "			LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "			INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "				CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "			CROSS APPLY ( \n"
                           + "				SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "				FROM OrderDetailInvoices AS odi \n"
                           + "				OUTER APPLY ( \n"
                           + "					SELECT odg.Id  \n"
                           + "					FROM OrderDetailIgredients AS odg \n"
                           + "					WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "				) odg \n"
                           + "				WHERE odi.InvoicesId = i.Id \n"
                           + "			)odi \n"
                           + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsInvoiced,0) = 0 \n"
                           + "		) fin \n"
                           + "	) res \n"
                           + "	ORDER BY res.Id \n"
                           + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisNotPaid] @posInfo BIGINT, @staffId BIGINT AS  \n"
                           + "BEGIN  \n"
                           + "	/*Gets a list of not paid invoices*/ \n"
                           + "	SELECT res.* \n"
                           + "	FROM ( \n"
                           + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription,  \n"
                           + "			pif.Id PosInfoId, fin.Abbreviation Abbreviation, fin.Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "			fin.Total, fin.Discount, fin.PaidTotal, odi.ItemsCount, fin.OrderNo OrderNo, fin.ReceiptNo, fin.InvoiceType, fin.IsInvoiced , \n"
                           + "			fin.IsVoided, fin.IsPaid, fin.Id InvoiceId, fin.Room, ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId \n"
                           + "		FROM ( \n"
                           + "			SELECT  i.[Day], it.Abbreviation Abbreviation, i.Cover Couver,  \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room, i.StaffId, i.TableId, \n"
                           + "				i.PosInfoId, i.Id  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "			LEFT OUTER JOIN Transactions AS t ON t.InvoicesId = i.Id AND t.EndOfDayId IS NULL \n"
                           + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND  \n"
                           + "				t.InvoicesId IS NULL \n"
                           + "			UNION ALL \n"
                           + "			SELECT i.[Day], it.Abbreviation Abbreviation, i.Cover Couver,  \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room, i.StaffId, i.TableId, \n"
                           + "				i.PosInfoId, i.Id  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,3,8,10,11,12) \n"
                           + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 1 AND ISNULL(i.IsVoided,0) = 0 AND ISNULL(i.IsPaid,0) = 1 \n"
                           + "		) fin \n"
                           + "		INNER JOIN PosInfo AS pif ON pif.Id = fin.PosInfoId \n"
                           + "		INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "		LEFT OUTER JOIN [Table] AS tb ON tb.Id = fin.TableId \n"
                           + "		INNER JOIN Staff AS s ON s.Id = fin.StaffId AND  \n"
                           + "			CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "		CROSS APPLY ( \n"
                           + "			SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "			FROM OrderDetailInvoices AS odi \n"
                           + "			OUTER APPLY ( \n"
                           + "				SELECT odg.Id  \n"
                           + "				FROM OrderDetailIgredients AS odg \n"
                           + "				WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "			) odg \n"
                           + "			WHERE odi.InvoicesId = fin.Id \n"
                           + "		)odi \n"
                           + "	) res \n"
                           + "	ORDER BY res.Id \n"
                           + "END");
            Ver_2_0_0_8.Add("ALTER PROCEDURE [dbo].[EndOfDayAnalysisNotPrinted] @posInfo BIGINT, @staffId BIGINT AS  \n"
                           + "BEGIN \n"
                           + "	/*Gets a list of not printed invoices */  \n"
                           + "	SELECT res.* \n"
                           + "	FROM ( \n"
                           + "		SELECT ROW_NUMBER() OVER (ORDER BY fin.ReceiptNo) Id, fin.* \n"
                           + "		FROM ( \n"
                           + "			SELECT  \n"
                           + "				i.[Day], pif.[Description] PosInfoDescription, d.[Description] DepartmentDescription, pif.Id PosInfoId, \n"
                           + "				it.Abbreviation Abbreviation, i.Cover Couver, s.FirstName + ' ' +s.LastName StaffName, s.Id StaffId, \n"
                           + "				(i.Total) Total, ISNULL(i.Discount,0) Discount, ISNULL(i.PaidTotal,0) PaidTotal, \n"
                           + "				odi.ItemsCount, i.OrderNo OrderNo, i.[Counter] ReceiptNo, it.[Type] InvoiceType, ISNULL(i.IsInvoiced,0) IsInvoiced , \n"
                           + "				ISNULL(i.IsVoided,0) IsVoided, ISNULL(i.IsPaid,0) IsPaid, i.Id InvoiceId, i.Rooms Room,  \n"
                           + "				ISNULL(tb.Code,'') TableCode, ISNULL(tb.Id,0) TableId  \n"
                           + "			FROM Invoices AS i \n"
                           + "			INNER JOIN InvoiceTypes AS it ON it.Id = i.InvoiceTypeId AND it.[Type] NOT IN (2,8,10,11,12) \n"
                           + "			INNER JOIN PosInfo AS pif ON pif.Id = i.PosInfoId \n"
                           + "			INNER JOIN Department AS d ON d.Id = pif.DepartmentId \n"
                           + "			LEFT OUTER JOIN [Table] AS tb ON tb.Id = i.TableId \n"
                           + "			INNER JOIN Staff AS s ON s.Id = i.StaffId AND  \n"
                           + "				CAST(s.Id AS VARCHAR(20)) LIKE CASE WHEN @staffId > 0 THEN CAST(@staffId AS VARCHAR(20)) ELSE '%' END \n"
                           + "			CROSS APPLY ( \n"
                           + "				SELECT ISNULL(COUNT(*),0)+ISNULL(COUNT(odg.Id),0) ItemsCount \n"
                           + "				FROM OrderDetailInvoices AS odi \n"
                           + "				OUTER APPLY ( \n"
                           + "					SELECT odg.Id  \n"
                           + "					FROM OrderDetailIgredients AS odg \n"
                           + "					WHERE odg.OrderDetailId = odi.Id	 \n"
                           + "				) odg \n"
                           + "				WHERE odi.InvoicesId = i.Id \n"
                           + "			)odi \n"
                           + "			WHERE i.PosInfoId = @posInfo AND i.EndOfDayId IS NULL AND ISNULL(i.IsPrinted,0) = 0 AND ISNULL(i.IsVoided,0) = 0 \n"
                           + "		) fin \n"
                           + "	) res \n"
                           + "	ORDER BY res.Id \n"
                           + "END");
        }
    }
}
