using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Symposium_DTOs.PosModel_Info
{
    [DisplayName("Ver : 2.0.0.4")]
    public class Version_2_0_0_4
    {
        public List<string> Ver_2_0_0_4 { get; }

        public Version_2_0_0_4()
        {
            Ver_2_0_0_4 = new List<string>();
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'CreditAccounts_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW CreditAccounts_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear, * \n"
                           + "	FROM CreditAccounts \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM CreditAccounts_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'CreditCodes_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW CreditCodes_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM CreditCodes \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM CreditCodes_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'CreditTransactions_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW CreditTransactions_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear, * \n"
                           + "	FROM CreditTransactions \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM CreditTransactions_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'EndOfDay_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW EndOfDay_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM EndOfDay \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM EndOfDay_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'EndOfDayDetail_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW EndOfDayDetail_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM EndOfDayDetail \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM EndOfDayDetail_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'EndOfDayPaymentAnalysis_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW EndOfDayPaymentAnalysis_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM EndOfDayPaymentAnalysis \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM EndOfDayPaymentAnalysis_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'EndOfDayVoidsAnalysis_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW EndOfDayVoidsAnalysis_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM EndOfDayVoidsAnalysis \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM EndOfDayVoidsAnalysis_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'EODAccountToPmsTransfer_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW EODAccountToPmsTransfer_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM EODAccountToPmsTransfer \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM EODAccountToPmsTransfer_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'ExternalLostOrders_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW ExternalLostOrders_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM ExternalLostOrders \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM ExternalLostOrders_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'HitPosOrders_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW HitPosOrders_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM HitPosOrders \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM HitPosOrders_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'Invoice_Guests_Trans_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW Invoice_Guests_Trans_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM Invoice_Guests_Trans \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM Invoice_Guests_Trans_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'Invoices_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW Invoices_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM Invoices \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM Invoices_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'InvoiceShippingDetails_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW InvoiceShippingDetails_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM InvoiceShippingDetails \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM InvoiceShippingDetails_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'KitchenInstructionLogger_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW KitchenInstructionLogger_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM KitchenInstructionLogger \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM KitchenInstructionLogger_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'Lockers_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW Lockers_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM Lockers \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM Lockers_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                            + "IF EXISTS(select 1 FROM sys.views where name = 'Loyalty_View') \n"
                            + "	SET @SQL = 'ALTER ' \n"
                            + "ELSE \n"
                            + "	SET @SQL = 'CREATE ' \n"
                            + "SET @SQL = @SQL + ' VIEW Loyalty_View AS \n"
                            + "	SELECT YEAR(GETDATE()) nYear,* \n"
                            + "	FROM Loyalty \n"
                            + "	UNION ALL \n"
                            + "	SELECT * \n"
                            + "	FROM Loyalty_Hist' \n"
                            + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'MealConsumption_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW MealConsumption_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM MealConsumption \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM MealConsumption_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OnlineRegistration_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OnlineRegistration_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OnlineRegistration \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OnlineRegistration_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'Order_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW Order_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM [Order] \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM Order_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderDetail_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderDetail_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderDetail \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderDetail_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderDetailIgredients_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderDetailIgredients_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderDetailIgredients \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderDetailIgredients_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderDetailIgredientVatAnal_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderDetailIgredientVatAnal_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderDetailIgredientVatAnal \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderDetailIgredientVatAnal_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderDetailInvoices_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderDetailInvoices_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderDetailInvoices \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderDetailInvoices_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderDetailVatAnal_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderDetailVatAnal_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderDetailVatAnal \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderDetailVatAnal_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrdersStaff_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrdersStaff_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrdersStaff \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrdersStaff_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'OrderStatus_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW OrderStatus_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM OrderStatus \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM OrderStatus_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'StoreMessages_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW StoreMessages_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM StoreMessages \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM StoreMessages_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'TablePaySuggestion_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW TablePaySuggestion_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM TablePaySuggestion \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM TablePaySuggestion_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'Transactions_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW Transactions_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM Transactions \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM Transactions_Hist' \n"
                           + "EXEC(@SQL)");
            Ver_2_0_0_4.Add("DECLARE @SQL VARCHAR(4000) \n"
                           + "IF EXISTS(select 1 FROM sys.views where name = 'TransferToPms_View') \n"
                           + "	SET @SQL = 'ALTER ' \n"
                           + "ELSE \n"
                           + "	SET @SQL = 'CREATE ' \n"
                           + "SET @SQL = @SQL + ' VIEW TransferToPms_View AS \n"
                           + "	SELECT YEAR(GETDATE()) nYear,* \n"
                           + "	FROM TransferToPms \n"
                           + "	UNION ALL \n"
                           + "	SELECT * \n"
                           + "	FROM TransferToPms_Hist' \n"
                           + "EXEC(@SQL)");
        }
    }
}
