using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Symposium_DTOs.PosModel_Info
{
    [DisplayName("Ver : 2.0.0.1")]
    public class Version_2_0_0_1
    {
        public List<string> Ver_2_0_0_1 { get; }

        public Version_2_0_0_1()
        {
            Ver_2_0_0_1 = new List<string>();
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_TransactionId' AND OBJECT_NAME(idx.OBJECT_ID) = 'CreditTransactions') \n"
                          + "	CREATE NONCLUSTERED INDEX [IX_TransactionId] ON [dbo].[CreditTransactions] ( [TransactionId] ASC )");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Guest_12_549576996__K1_5_6_9_10_11_12' AND OBJECT_NAME(idx.OBJECT_ID) = 'Guest') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Guest_12_549576996__K1_5_6_9_10_11_12] ON [dbo].[Guest]  \n"
                           + "	( \n"
                           + "		[Id] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Room], \n"
                           + "	[RoomId], \n"
                           + "	[ReservationCode], \n"
                           + "	[ProfileNo], \n"
                           + "	[FirstName], \n"
                           + "	[LastName])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoice_Guests_Trans_6_1029578706__K4_K1_K3' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoice_Guests_Trans') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoice_Guests_Trans_6_1029578706__K4_K1_K3] ON [dbo].[Invoice_Guests_Trans]  \n"
                           + "	( \n"
                           + "		[TransactionId] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[GuestId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoice_Guests_Trans_8_965578478__K3_K4_2' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoice_Guests_Trans') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoice_Guests_Trans_8_965578478__K3_K4_2] ON [dbo].[Invoice_Guests_Trans]  \n"
                           + "	( \n"
                           + "		[GuestId] ASC, \n"
                           + "		[TransactionId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [InvoiceId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoice_Guests_Trans_9_677577452__K3_K4' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoice_Guests_Trans') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoice_Guests_Trans_9_677577452__K3_K4] ON [dbo].[Invoice_Guests_Trans]  \n"
                           + "	( \n"
                           + "		[GuestId] ASC, \n"
                           + "		[TransactionId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='Invoice_Guests_TransTransactionId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoice_Guests_Trans') \n"
                           + "	CREATE NONCLUSTERED INDEX [Invoice_Guests_TransTransactionId_IDX] ON [dbo].[Invoice_Guests_Trans]  \n"
                           + "	( \n"
                           + "		[TransactionId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_116_366624349__K1_K19_K22_K3_K13' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_116_366624349__K1_K19_K22_K3_K13] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[InvoiceTypeId] ASC, \n"
                           + "		[StaffId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_116_366624349__K1_K19_K22_K3_K16_K13' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_116_366624349__K1_K19_K22_K3_K16_K13] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[InvoiceTypeId] ASC, \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[StaffId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_116_366624349__K3_K19_K22_K16_K13_K1_4_5_6_8_9_10_12_14_17_18_20_21_23' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_116_366624349__K3_K19_K22_K16_K13_K1_4_5_6_8_9_10_12_14_17_18_20_21_23] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[InvoiceTypeId] ASC, \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[StaffId] ASC, \n"
                           + "		[Id] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[Cover], \n"
                           + "	[PdaModuleId], \n"
                           + "	[ClientPosId], \n"
                           + "	[PosInfoDetailId], \n"
                           + "	[IsVoided], \n"
                           + "	[DiscountRemark])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_6_1061578820__K16_K19_K22_K1_K3_K13_4_5_6_8_9_10_12_14_17_18_20_21_23' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_6_1061578820__K16_K19_K22_K1_K3_K13_4_5_6_8_9_10_12_14_17_18_20_21_23] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[InvoiceTypeId] ASC, \n"
                           + "		[StaffId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[Cover], \n"
                           + "	[PdaModuleId], \n"
                           + "	[ClientPosId], \n"
                           + "	[PosInfoDetailId], \n"
                           + "	[IsVoided], \n"
                           + "	[DiscountRemark])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_8_997578592__K1_K22_K3_16_19_20' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_8_997578592__K1_K22_K3_16_19_20] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[InvoiceTypeId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [PosInfoId], \n"
                           + "	[EndOfDayId], \n"
                           + "	[PosInfoDetailId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Invoices_8_997578592__K16_K22_K3_1_4_5_6_8_9_10_12_13_14_17_18_19_20_21_23' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Invoices_8_997578592__K16_K22_K3_1_4_5_6_8_9_10_12_13_14_17_18_19_20_21_23] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[InvoiceTypeId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[StaffId], \n"
                           + "	[Cover], \n"
                           + "	[PdaModuleId], \n"
                           + "	[ClientPosId], \n"
                           + "	[EndOfDayId], \n"
                           + "	[PosInfoDetailId], \n"
                           + "	[IsVoided], \n"
                           + "	[DiscountRemark])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='InvoicesEndOfDayIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [InvoicesEndOfDayIsDeleted_IDX] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[Description], \n"
                           + "	[InvoiceTypeId], \n"
                           + "	[Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[StaffId], \n"
                           + "	[Cover], \n"
                           + "	[TableId], \n"
                           + "	[PosInfoId], \n"
                           + "	[IsVoided])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='InvoicesPosInfoIdEndOfDayIdIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [InvoicesPosInfoIdEndOfDayIdIsDeleted_IDX] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[EndOfDayId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[Description], \n"
                           + "	[InvoiceTypeId], \n"
                           + "	[Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[StaffId], \n"
                           + "	[Cover], \n"
                           + "	[TableId], \n"
                           + "	[IsVoided])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='InvoicesPosInfoIdIsDeleted-IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Invoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [InvoicesPosInfoIdIsDeleted-IDX] ON [dbo].[Invoices]  \n"
                           + "	( \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[Description], \n"
                           + "	[InvoiceTypeId], \n"
                           + "	[Counter], \n"
                           + "	[Day], \n"
                           + "	[IsPrinted], \n"
                           + "	[Total], \n"
                           + "	[Discount], \n"
                           + "	[Vat], \n"
                           + "	[Net], \n"
                           + "	[StaffId], \n"
                           + "	[Cover], \n"
                           + "	[TableId], \n"
                           + "	[EndOfDayId], \n"
                           + "	[IsVoided])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_EndOfDayId' AND OBJECT_NAME(idx.OBJECT_ID) = 'Lockers') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_EndOfDayId] ON [dbo].[Lockers]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_OnlineRegistration_FirstName' AND OBJECT_NAME(idx.OBJECT_ID) = 'OnlineRegistration') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_OnlineRegistration_FirstName] ON [dbo].[OnlineRegistration]  \n"
                           + "	( \n"
                           + "		[FirtName] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_OnlineRegistration_LastName' AND OBJECT_NAME(idx.OBJECT_ID) = 'OnlineRegistration') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_OnlineRegistration_LastName] ON [dbo].[OnlineRegistration]  \n"
                           + "	( \n"
                           + "		[LastName] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_OnlineRegistration_Status' AND OBJECT_NAME(idx.OBJECT_ID) = 'OnlineRegistration') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_OnlineRegistration_Status] ON [dbo].[OnlineRegistration]  \n"
                           + "	( \n"
                           + "		[Status] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Order_6_1317579732__K1_K2' AND OBJECT_NAME(idx.OBJECT_ID) = 'Order') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Order_6_1317579732__K1_K2] ON [dbo].[Order]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[OrderNo] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderEODIDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Order') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderEODIDX] ON [dbo].[Order]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_116_1602104748__K1_K7_K8_K15_K21_K2' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_116_1602104748__K1_K7_K8_K15_K21_K2] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[TableId] ASC, \n"
                           + "		[Status] ASC, \n"
                           + "		[PaidStatus] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[OrderId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_116_1602104748__K15_K8_K1_K2_K4_K5_K6_K7_3_11_12_14_17_21' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_116_1602104748__K15_K8_K1_K2_K4_K5_K6_K7_3_11_12_14_17_21] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[PaidStatus] ASC, \n"
                           + "		[Status] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[OrderId] ASC, \n"
                           + "		[KitchenId] ASC, \n"
                           + "		[KdsId] ASC, \n"
                           + "		[PreparationTime] ASC, \n"
                           + "		[TableId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [ProductId], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[Qty], \n"
                           + "	[Discount], \n"
                           + "	[TotalAfterDiscount], \n"
                           + "	[IsDeleted])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_116_1602104748__K7_K15_K8_K1_K2_K3_K11_K21_K17_K12_K14_K4_K5_K6_K20' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_116_1602104748__K7_K15_K8_K1_K2_K3_K11_K21_K17_K12_K14_K4_K5_K6_K20] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[TableId] ASC, \n"
                           + "		[PaidStatus] ASC, \n"
                           + "		[Status] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[OrderId] ASC, \n"
                           + "		[ProductId] ASC, \n"
                           + "		[PriceListDetailId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[TotalAfterDiscount] ASC, \n"
                           + "		[Qty] ASC, \n"
                           + "		[Discount] ASC, \n"
                           + "		[KitchenId] ASC, \n"
                           + "		[KdsId] ASC, \n"
                           + "		[PreparationTime] ASC, \n"
                           + "		[Guid] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_116_1602104748__K7_K8_K15_K21_1_2' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_116_1602104748__K7_K8_K15_K21_1_2] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[TableId] ASC, \n"
                           + "		[Status] ASC, \n"
                           + "		[PaidStatus] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_6_1349579846__K1_K2' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_6_1349579846__K1_K2] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[OrderId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetail_6_1349579846__K1_K21_K17' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetail_6_1349579846__K1_K21_K17] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[TotalAfterDiscount] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='<Name of Missing Index, sysname,>' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[Status] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[PaidStatus])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailInvoicesReceiptDetails_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailInvoicesReceiptDetails_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[ProductId], \n"
                           + "	[KitchenId], \n"
                           + "	[KdsId], \n"
                           + "	[PreparationTime], \n"
                           + "	[TableId], \n"
                           + "	[Status], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[SalesTypeId], \n"
                           + "	[PaidStatus], \n"
                           + "	[Guid])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailIsDeleted' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailIsDeleted] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[ProductId], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[SalesTypeId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailIsDeleted_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[ProductId], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[SalesTypeId], \n"
                           + "	[TotalAfterDiscount])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailOrderIdIsDelettedIDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailOrderIdIsDelettedIDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[OrderId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[Status], \n"
                           + "	[PaidStatus])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailProductIdIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailProductIdIsDeleted_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[ProductId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[SalesTypeId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailSalesTypeIdIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailSalesTypeIdIsDeleted_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[SalesTypeId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[ProductId], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[TotalAfterDiscount])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='Test1_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [Test1_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[Status] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[OrderId], \n"
                           + "	[ProductId], \n"
                           + "	[KitchenId], \n"
                           + "	[TableId], \n"
                           + "	[Price], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[Qty], \n"
                           + "	[Discount], \n"
                           + "	[PaidStatus], \n"
                           + "	[TotalAfterDiscount], \n"
                           + "	[Couver], \n"
                           + "	[Guid])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='Test3_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [Test3_IDX] ON [dbo].[OrderDetail]  \n"
                           + "	( \n"
                           + "		[OrderId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[ProductId], \n"
                           + "	[KitchenId], \n"
                           + "	[TableId], \n"
                           + "	[Status], \n"
                           + "	[Price], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[Qty], \n"
                           + "	[Discount], \n"
                           + "	[PaidStatus], \n"
                           + "	[TotalAfterDiscount], \n"
                           + "	[Couver], \n"
                           + "	[Guid])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetailIgredients_116_1906105831__K6_K9_K2_K3_K8_K10_1_7' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailIgredients') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetailIgredients_116_1906105831__K6_K9_K2_K3_K8_K10_1_7] ON [dbo].[OrderDetailIgredients]  \n"
                           + "	( \n"
                           + "		[OrderDetailId] ASC, \n"
                           + "		[TotalAfterDiscount] ASC, \n"
                           + "		[IngredientId] ASC, \n"
                           + "		[Qty] ASC, \n"
                           + "		[Discount] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[PriceListDetailId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailIgredientsOrderDetailId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailIgredients') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailIgredientsOrderDetailId_IDX] ON [dbo].[OrderDetailIgredients]  \n"
                           + "	( \n"
                           + "		[OrderDetailId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[IngredientId], \n"
                           + "	[Qty], \n"
                           + "	[PriceListDetailId], \n"
                           + "	[Discount], \n"
                           + "	[TotalAfterDiscount])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetailIgredientVatAnal_116_2050106344__K2_K7_K4_K6_K8_K9_5' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailIgredientVatAnal') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetailIgredientVatAnal_116_2050106344__K2_K7_K4_K6_K8_K9_5] ON [dbo].[OrderDetailIgredientVatAnal]  \n"
                           + "	( \n"
                           + "		[OrderDetailIgredientsId] ASC, \n"
                           + "		[VatId] ASC, \n"
                           + "		[Net] ASC, \n"
                           + "		[VatAmount] ASC, \n"
                           + "		[TaxId] ASC, \n"
                           + "		[TaxAmount] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [VatRate])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetailIgredientVatAnal_116_2050106344__K7_K2_K4_K6_K8_K9_5' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailIgredientVatAnal') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetailIgredientVatAnal_116_2050106344__K7_K2_K4_K6_K8_K9_5] ON [dbo].[OrderDetailIgredientVatAnal]  \n"
                           + "	( \n"
                           + "		[VatId] ASC, \n"
                           + "		[OrderDetailIgredientsId] ASC, \n"
                           + "		[Net] ASC, \n"
                           + "		[VatAmount] ASC, \n"
                           + "		[TaxId] ASC, \n"
                           + "		[TaxAmount] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [VatRate])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_EndOfDayId' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailInvoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_EndOfDayId] ON [dbo].[OrderDetailInvoices]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_OrderDetailIgredientsId' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailInvoices') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_OrderDetailIgredientsId] ON [dbo].[OrderDetailInvoices]  \n"
                           + "	( \n"
                           + "		[OrderDetailIgredientsId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetailVatAnal_116_2018106230__K7_K2_K4_K6_K8_K9_5' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailVatAnal') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetailVatAnal_116_2018106230__K7_K2_K4_K6_K8_K9_5] ON [dbo].[OrderDetailVatAnal]  \n"
                           + "	( \n"
                           + "		[VatId] ASC, \n"
                           + "		[OrderDetailId] ASC, \n"
                           + "		[Net] ASC, \n"
                           + "		[VatAmount] ASC, \n"
                           + "		[TaxId] ASC, \n"
                           + "		[TaxAmount] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [VatRate])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_OrderDetailVatAnal_6_1477580302__K2_K8_K7_K4_K6_K9_5' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailVatAnal') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_OrderDetailVatAnal_6_1477580302__K2_K8_K7_K4_K6_K9_5] ON [dbo].[OrderDetailVatAnal]  \n"
                           + "	( \n"
                           + "		[OrderDetailId] ASC, \n"
                           + "		[TaxId] ASC, \n"
                           + "		[VatId] ASC, \n"
                           + "		[Net] ASC, \n"
                           + "		[VatAmount] ASC, \n"
                           + "		[TaxAmount] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [VatRate])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderDetailVatAnalOrderIdVatId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderDetailVatAnal') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderDetailVatAnalOrderIdVatId_IDX] ON [dbo].[OrderDetailVatAnal]  \n"
                           + "	( \n"
                           + "		[OrderDetailId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [VatId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='OrderStatusOrderId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'OrderStatus') \n"
                           + "	CREATE NONCLUSTERED INDEX [OrderStatusOrderId_IDX] ON [dbo].[OrderStatus]  \n"
                           + "	( \n"
                           + "		[OrderId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0-Receipe, 1-Extras', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PageButtonDetail', @level2type = N'COLUMN', @level2name = N'Type';");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Product_12_1925581898__K11_K1' AND OBJECT_NAME(idx.OBJECT_ID) = 'Product') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Product_12_1925581898__K11_K1] ON [dbo].[Product]  \n"
                           + "	( \n"
                           + "		[ProductCategoryId] ASC, \n"
                           + "		[Id] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='ProductProductCategoryId-IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Product') \n"
                           + "	CREATE NONCLUSTERED INDEX [ProductProductCategoryId-IDX] ON [dbo].[Product]  \n"
                           + "	( \n"
                           + "		[ProductCategoryId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Transactions_116_1442104178__K18_K19_K1_K10_K3_6_7_16' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Transactions_116_1442104178__K18_K19_K1_K10_K3_6_7_16] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[InvoicesId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[AccountId] ASC, \n"
                           + "		[PosInfoId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [TransactionType], \n"
                           + "	[Amount], \n"
                           + "	[EndOfDayId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Transactions_6_706101556__K18_K1_K10_K3_K19_6_7_16' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Transactions_6_706101556__K18_K1_K10_K3_K19_6_7_16] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[InvoicesId] ASC, \n"
                           + "		[Id] ASC, \n"
                           + "		[AccountId] ASC, \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [TransactionType], \n"
                           + "	[Amount], \n"
                           + "	[EndOfDayId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_Transactions_9_290100074__K10_K19_K3_K1_6_7_16_18' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_Transactions_9_290100074__K10_K19_K3_K1_6_7_16_18] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[AccountId] ASC, \n"
                           + "		[IsDeleted] ASC, \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[Id] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [TransactionType], \n"
                           + "	[Amount], \n"
                           + "	[EndOfDayId], \n"
                           + "	[InvoicesId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_EndOfDayId' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_EndOfDayId] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='PosInfoIdTransactionTypeEndOfDayId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [PosInfoIdTransactionTypeEndOfDayId_IDX] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[PosInfoId] ASC, \n"
                           + "		[TransactionType] ASC, \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='TransactionInvoiceId_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [TransactionInvoiceId_IDX] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[InvoicesId] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Id], \n"
                           + "	[StaffId], \n"
                           + "	[Amount], \n"
                           + "	[AccountId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='TransactionsAccountIdInvoicesIdIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [TransactionsAccountIdInvoicesIdIsDeleted_IDX] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[AccountId] ASC, \n"
                           + "		[InvoicesId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	) \n"
                           + "	INCLUDE ( [Amount], \n"
                           + "	[EndOfDayId])");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='TransactionsInvoicesIdIsDeleted_IDX' AND OBJECT_NAME(idx.OBJECT_ID) = 'Transactions') \n"
                           + "	CREATE NONCLUSTERED INDEX [TransactionsInvoicesIdIsDeleted_IDX] ON [dbo].[Transactions]  \n"
                           + "	( \n"
                           + "		[InvoicesId] ASC, \n"
                           + "		[IsDeleted] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_TransferMappingsId' AND OBJECT_NAME(idx.OBJECT_ID) = 'TransferMappingDetails') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_TransferMappingsId] ON [dbo].[TransferMappingDetails]  \n"
                           + "	( \n"
                           + "		[TransferMappingsId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0-Xrewstiko, 1-endOfDay', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TransferToPms', @level2type = N'COLUMN', @level2name = N'TransferType'; \n"
                           + "");
            Ver_2_0_0_1.Add("EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Enum for  \n"
                           + "POS \n"
                           + "KDS \n"
                           + "TABLES \n"
                           + "DELIVERY', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ValidModules', @level2type = N'COLUMN', @level2name = N'ModuleType'; \n"
                           + "");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_PricelistDetail_116_802101898__K1_K2_K5' AND OBJECT_NAME(idx.OBJECT_ID) = 'PricelistDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_PricelistDetail_116_802101898__K1_K2_K5] ON [dbo].[PricelistDetail]  \n"
                           + "	( \n"
                           + "		[Id] ASC, \n"
                           + "		[PricelistId] ASC, \n"
                           + "		[Price] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='_dta_index_PricelistDetail_12_1861581670__K4_K5' AND OBJECT_NAME(idx.OBJECT_ID) = 'PricelistDetail') \n"
                           + "	CREATE NONCLUSTERED INDEX [_dta_index_PricelistDetail_12_1861581670__K4_K5] ON [dbo].[PricelistDetail]  \n"
                           + "	( \n"
                           + "		[IngredientId] ASC, \n"
                           + "		[Price] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_EndOfDayId' AND OBJECT_NAME(idx.OBJECT_ID) = 'TransferToPms') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_EndOfDayId] ON [dbo].[TransferToPms]  \n"
                           + "	( \n"
                           + "		[EndOfDayId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Home, Company ...', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Delivery_AddressTypes', @level2type = N'COLUMN', @level2name = N'Descr';");
            Ver_2_0_0_1.Add("EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0 : Draxmiki - 1 : Posostiaia', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Discount', @level2type = N'COLUMN', @level2name = N'Type';");
            Ver_2_0_0_1.Add("IF EXISTS(SELECT 1 FROM sys.[columns] c WHERE c.name = 'Datetime' AND OBJECT_NAME(c.[object_id]) = 'EndOfDay') \n"
                          + "	ALTER TABLE [dbo].[EndOfDay] DROP COLUMN [Datetime]");
            Ver_2_0_0_1.Add("IF EXISTS(SELECT 1 FROM sys.foreign_keys fk WHERE fk.name = 'FK_RegionLockerProduct_Region' AND OBJECT_NAME(fk.parent_object_id) = 'RegionLockerProduct') \n"
                          + "	ALTER TABLE [dbo].[RegionLockerProduct] DROP CONSTRAINT [FK_RegionLockerProduct_Region]");
            Ver_2_0_0_1.Add("IF EXISTS(SELECT 1 FROM sys.[columns] c WHERE c.name = 'RegionId' AND OBJECT_NAME(c.[object_id]) = 'RegionLockerProduct') \n"
                          + "	ALTER TABLE [dbo].[RegionLockerProduct] DROP COLUMN [RegionId]");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_Payrole_ActionDate' AND OBJECT_NAME(idx.OBJECT_ID) = 'Payrole') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_Payrole_ActionDate] ON [dbo].[Payrole]  \n"
                           + "	( \n"
                           + "		[ActionDate] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_Payrole_DayStaff' AND OBJECT_NAME(idx.OBJECT_ID) = 'Payrole') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_Payrole_DayStaff] ON [dbo].[Payrole]  \n"
                           + "	( \n"
                           + "		[ActionDate] ASC, \n"
                           + "      [ShopId] ASC, \n"
                           + "      [StaffId] ASC, \n"
                           + "      [PosInfoId] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_Payrole_Identification' AND OBJECT_NAME(idx.OBJECT_ID) = 'Payrole') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_Payrole_Identification] ON [dbo].[Payrole]  \n"
                           + "	( \n"
                           + "		[Identification] ASC \n"
                           + "	)");
            Ver_2_0_0_1.Add("IF NOT EXISTS (SELECT 1 FROM sys.indexes idx WHERE idx.name='IX_Payrole_StaffId' AND OBJECT_NAME(idx.OBJECT_ID) = 'Payrole') \n"
                           + "	CREATE NONCLUSTERED INDEX [IX_Payrole_StaffId] ON [dbo].[Payrole]  \n"
                           + "	( \n"
                           + "		[StaffId] ASC \n"
                           + "	)");
        }
    }
}
