//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symposium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symposium.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η γεωγραφική θέση δεν είναι ακριβής. Ελέγξτε τη διεύθυνση..
        /// </summary>
        public static string ADDRAPPROXIMATE {
            get {
                return ResourceManager.GetString("ADDRAPPROXIMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η διεύθυνση δεν έχει αντιστοιχηθεί ή δεν είναι έγκυρη.
        /// </summary>
        public static string ADDRESSNOTVALID {
            get {
                return ResourceManager.GetString("ADDRESSNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η διεύθυνση είναι ελλειπής.
        /// </summary>
        public static string ADDRNOZIPNOREGION {
            get {
                return ResourceManager.GetString("ADDRNOZIPNOREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν υπάρχει πελάτης στη παραγγελία.
        /// </summary>
        public static string ANONYMOUSCUSTOMERNULLMODEL {
            get {
                return ResourceManager.GetString("ANONYMOUSCUSTOMERNULLMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το barcode {0} υπάρχει.
        /// </summary>
        public static string BARCODEEXISTS {
            get {
                return ResourceManager.GetString("BARCODEEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο Πελάτης δε βρέθηκε..
        /// </summary>
        public static string CUSTOMERNOTFOUND {
            get {
                return ResourceManager.GetString("CUSTOMERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ακύρωση της παραγγελίες δεν μπορεί να πραγματοποιηθεί!.
        /// </summary>
        public static string DACANCELFAILED {
            get {
                return ResourceManager.GetString("DACANCELFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την εισαγώγη DA Customer Message.
        /// </summary>
        public static string DACUSTMESSAGEINSERTION {
            get {
                return ResourceManager.GetString("DACUSTMESSAGEINSERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ενημέρωση DA Customer Message.
        /// </summary>
        public static string DACUSTMESSAGEUPDATE {
            get {
                return ResourceManager.GetString("DACUSTMESSAGEUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την επιλογή μηνυμάτων.
        /// </summary>
        public static string DACUSTOMERMESSAGES {
            get {
                return ResourceManager.GetString("DACUSTOMERMESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά τη φόρτωση των μηνυμάτων!.
        /// </summary>
        public static string DAMESSAGES {
            get {
                return ResourceManager.GetString("DAMESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η διαγραφή απέτυχε.
        /// </summary>
        public static string DELETEFAILED {
            get {
                return ResourceManager.GetString("DELETEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε Δελτίο Παραγγελίας για την παραγγελία {0}.
        /// </summary>
        public static string DELIVERY_AGENT_INVOICE_NOT_FOUND_FOR_UPDATE {
            get {
                return ResourceManager.GetString("DELIVERY_AGENT_INVOICE_NOT_FOUND_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η παραγγελία {0} δεν μπορεί να ματαβληθεί γιατί έχει ολοκληρωθεί.
        /// </summary>
        public static string DELIVERY_ORDER_CAN_NOT_BE_UPDATED {
            get {
                return ResourceManager.GetString("DELIVERY_ORDER_CAN_NOT_BE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά τη διαγραφή πελάτη Delivery.
        /// </summary>
        public static string DELIVERYCUSTOMERDELETE {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ανάγνωση πελάτη Delivery με id.
        /// </summary>
        public static string DELIVERYCUSTOMERDETBYIDS {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERDETBYIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την εισαγωγή πελάτη Delivery.
        /// </summary>
        public static string DELIVERYCUSTOMERINSERT {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά τη φόρτωση Lookup δεδομένων  Delivery.
        /// </summary>
        public static string DELIVERYCUSTOMERLOOKUPS {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERLOOKUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την αναζήτηση πελατών Delivery σε σελίδες.
        /// </summary>
        public static string DELIVERYCUSTOMERSEARCHPAGED {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERSEARCHPAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ανανέωση πελάτη Delivery.
        /// </summary>
        public static string DELIVERYCUSTOMERUPDATE {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Guest from Delivery Customer.
        /// </summary>
        public static string DELIVERYCUSTOMERUPDATEGUEST {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERUPDATEGUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ανανέωση / εισαγωγή πελάτη Delivery με ExtCustId.
        /// </summary>
        public static string DELIVERYCUSTOMERUPSERTCUSTOMEREXTCUSTID {
            get {
                return ResourceManager.GetString("DELIVERYCUSTOMERUPSERTCUSTOMEREXTCUSTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά τη φόρτωση Delivery παραγγελιών .
        /// </summary>
        public static string DELIVERYORDERSPAGGEDBYSTATE {
            get {
                return ResourceManager.GetString("DELIVERYORDERSPAGGEDBYSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά τη φόρτωση Μετρητών Delivery παραγγελιών.
        /// </summary>
        public static string DELIVERYORDERSSTATECOUNTS {
            get {
                return ResourceManager.GetString("DELIVERYORDERSSTATECOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ανανέωση στοιχείων αποστολής παραγγελίας σε αλλαγή διεύθυνσης.
        /// </summary>
        public static string DELIVERYORDERSUPDATESHIPPINGCOORDS {
            get {
                return ResourceManager.GetString("DELIVERYORDERSUPDATESHIPPINGCOORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αφαίρεση διπλών τιμών απέτυχε.
        /// </summary>
        public static string DUPLICATEVALUESREMOVEDFAILED {
            get {
                return ResourceManager.GetString("DUPLICATEVALUESREMOVEDFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορούν να αποθηκευτούν ήδη υπάρχουσες καταχωρήσεις..
        /// </summary>
        public static string ENTRIESALREADYEXISTS {
            get {
                return ResourceManager.GetString("ENTRIESALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το End of day Id  είναι null!.
        /// </summary>
        public static string EODIDNULL {
            get {
                return ResourceManager.GetString("EODIDNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προέκυψε ένα σφάλμα!.
        /// </summary>
        public static string ERROROCCURED {
            get {
                return ResourceManager.GetString("ERROROCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο Εκτυπωτής Καταστήματος (extecr) {0} δεν είναι συνδεμένος.
        /// </summary>
        public static string EXTECRNOTCONNECTED {
            get {
                return ResourceManager.GetString("EXTECRNOTCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο εκτυπωτής &apos;{0}&apos; δεν βρέθηκε.
        /// </summary>
        public static string EXTECRNOTFOUND {
            get {
                return ResourceManager.GetString("EXTECRNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απέτυχε.
        /// </summary>
        public static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλαμα κατά τη διαγραφή των μηνυμάτων!.
        /// </summary>
        public static string FAILEDDAMESSAGESDELETE {
            get {
                return ResourceManager.GetString("FAILEDDAMESSAGESDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την Διαγραφή Προτάσεων.
        /// </summary>
        public static string FAILEDDELETEPROMOTIONS {
            get {
                return ResourceManager.GetString("FAILEDDELETEPROMOTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την Εισαγωγή Προτάσεων.
        /// </summary>
        public static string FAILEDINSERTPROMOTIONS {
            get {
                return ResourceManager.GetString("FAILEDINSERTPROMOTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την ανάκτηση Προτάσεων.
        /// </summary>
        public static string FAILEDLOADPROMOTIONS {
            get {
                return ResourceManager.GetString("FAILEDLOADPROMOTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα κατά την τροποποίηση Προτάσεων.
        /// </summary>
        public static string FAILEDUPDATEPROMOTIONS {
            get {
                return ResourceManager.GetString("FAILEDUPDATEPROMOTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο αριθμός της τωρινής σελίδας πρέπει να είναι 0 ή μεγαλύτερος.
        /// </summary>
        public static string GREATERNUMBER {
            get {
                return ResourceManager.GetString("GREATERNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το μέγεθος της σελίδας πρέπει να είναι 1 ή μεγαλύτερο.
        /// </summary>
        public static string GREATERPAGELENGTH {
            get {
                return ResourceManager.GetString("GREATERPAGELENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κατάστημα αυτή τη στιγμή δεν εξηπηρετεί τη περιοχή για παραγγελίες delivery. Δοκιμάστε take out..
        /// </summary>
        public static string INACTIVEPOLYGON {
            get {
                return ResourceManager.GetString("INACTIVEPOLYGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος μοντέλο για καταχώρηση.
        /// </summary>
        public static string INSERTBADMODEL {
            get {
                return ResourceManager.GetString("INSERTBADMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η καταχώρηση απέτυχε.
        /// </summary>
        public static string INSERTFAILED {
            get {
                return ResourceManager.GetString("INSERTFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη έγκυρη κάρτα μοντέλου!.
        /// </summary>
        public static string INVALIDCARDMODEL {
            get {
                return ResourceManager.GetString("INVALIDCARDMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη έγκυρος τομέας ημερομηνίας: {0} {1}.
        /// </summary>
        public static string INVALIDDATESECTOR {
            get {
                return ResourceManager.GetString("INVALIDDATESECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος τιμοκατάλογος στο είδος {0}.
        /// </summary>
        public static string INVALIDPRICELISTFORITEM {
            get {
                return ResourceManager.GetString("INVALIDPRICELISTFORITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη έγκυρος τομέας δωματίου: {0}.
        /// </summary>
        public static string INVALIDROOMSECTOR {
            get {
                return ResourceManager.GetString("INVALIDROOMSECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ακύρωση παραστατικού απέτυχε!.
        /// </summary>
        public static string INVOICECANCELATIONFAILED {
            get {
                return ResourceManager.GetString("INVOICECANCELATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το παραστατικό δεν μπορεί να ακυρωθεί!.
        /// </summary>
        public static string INVOICECANNOTCANCELED {
            get {
                return ResourceManager.GetString("INVOICECANNOTCANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο τύπος του παραστατικού δεν βρέθηκε για το InvoiceTypeId: {0}.
        /// </summary>
        public static string INVOICETYPENOTFOUND {
            get {
                return ResourceManager.GetString("INVOICETYPENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορεί να πραγματοποιηθεί προσθήκη επιπλέον πόντων διότι το άθροισμα τους ξεπερνάει το μέγιστο επιτρεπτό όριο.
        /// </summary>
        public static string MAXLOYALTYPOINTSLIMITREACHED {
            get {
                return ResourceManager.GetString("MAXLOYALTYPOINTSLIMITREACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει δηλωθεί διεύθυνση αποστολής.
        /// </summary>
        public static string MISSING_DELIVERY_ADDRESS {
            get {
                return ResourceManager.GetString("MISSING_DELIVERY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει δηλωθεί τηλέφωνο.
        /// </summary>
        public static string MISSING_DELIVERY_PHONE {
            get {
                return ResourceManager.GetString("MISSING_DELIVERY_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παραγγελία τυπου πληρωμής τιμολόγιο χωρίς στοιχεία παραστατικού.
        /// </summary>
        public static string MISSING_INVOICE_INFO {
            get {
                return ResourceManager.GetString("MISSING_INVOICE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λείπει η κατηγορία προϊόντος για την παραγγελία {0} και το είδος {1}.
        /// </summary>
        public static string MISSING_PRODUCTCATEGORY_FOR_DA {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTCATEGORY_FOR_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λείπει ο κωδικός προϊόντος για την παραγγελία {0} και το είδος {1}.
        /// </summary>
        public static string MISSING_PRODUCTCODE_FOR_DA {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTCODE_FOR_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λείπει το προϊόν για την παραγγελία {0} και το είδος {1}.
        /// </summary>
        public static string MISSING_PRODUCTID_FOR_DA {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTID_FOR_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λείπει ο τιμοκατάλογος προϊόντος για την παραγγελία {0} και το είδος {1}.
        /// </summary>
        public static string MISSING_PRODUCTPRICELIST_FOR_DA {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTPRICELIST_FOR_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν  υπάρχουν προϊόντα για την παραγγελία.
        /// </summary>
        public static string MISSING_PRODUCTS_FOR_DELIVERYAGENT_ORDER {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTS_FOR_DELIVERYAGENT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λείπει το Φ.Π.Α. προϊόντος για την παραγγελία {0} και το είδος {1}.
        /// </summary>
        public static string MISSING_PRODUCTVAT_FOR_DA {
            get {
                return ResourceManager.GetString("MISSING_PRODUCTVAT_FOR_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν είναι δυνατή η δημιουργία μιας περιγραφής μοντέλου. Το ίδιο όνομα μοντέλου &apos;{0}&apos; βρέθηκε για τους τύπους &apos;{1}&apos; και &apos;{2}&apos;. Χρησιμοποίησε το [ModelName] χαρακτηριστικό για να αλλάξεις το όνομα του μοντέλου τουλάχιστον για έναν απο τους τύπους έτσι ώστε να έχει ένα μοναδικό όνομα..
        /// </summary>
        public static string MODELDESCRIPTIONNOTCREATED {
            get {
                return ResourceManager.GetString("MODELDESCRIPTIONNOTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το υπόλοιπο των ανθρώπων είναι αρνητικό.
        /// </summary>
        public static string NEGATIVEBALANCE {
            get {
                return ResourceManager.GetString("NEGATIVEBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει καθοριστεί ημερομηνία λήξης..
        /// </summary>
        public static string NOCLOSINGDATE {
            get {
                return ResourceManager.GetString("NOCLOSINGDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δε βρέθηκε πρόσθετο με κωδ. &apos;{0}&apos;.
        /// </summary>
        public static string NOEXTRACODE {
            get {
                return ResourceManager.GetString("NOEXTRACODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν δόθηκε παράμετρος id για εκτέλεση.
        /// </summary>
        public static string NOQUERYIDEXECUTED {
            get {
                return ResourceManager.GetString("NOQUERYIDEXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν δόθηκε λίστα αναζήτησης για εκτέλεση.
        /// </summary>
        public static string NOQUERYLISTEXECUTED {
            get {
                return ResourceManager.GetString("NOQUERYLISTEXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε StoreId ή PosId.
        /// </summary>
        public static string NOSTOREIDORPOSID {
            get {
                return ResourceManager.GetString("NOSTOREIDORPOSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκε.
        /// </summary>
        public static string NOTFOUND {
            get {
                return ResourceManager.GetString("NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η παράμετρος δεν μπορεί να είναι null: {0}.
        /// </summary>
        public static string NULLARGUMENT {
            get {
                return ResourceManager.GetString("NULLARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Παραγγελία (order body) είναι κενη.
        /// </summary>
        public static string ORDERBODYEMPTY {
            get {
                return ResourceManager.GetString("ORDERBODYEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H παραγγελία δεν μπορεί να μεταβληθεί.
        /// </summary>
        public static string ORDERCANNOTBEUPDATED {
            get {
                return ResourceManager.GetString("ORDERCANNOTBEUPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αυτή τη στιγμή δεν μπορούμε να σας εξυπηρετήσουμε προσπαθήστε αργότερα.
        /// </summary>
        public static string OUTOFTRADINGHOURS {
            get {
                return ResourceManager.GetString("OUTOFTRADINGHOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πρέπει να εισαχθεί τουλάχιστον ένα τηλέφωνο.
        /// </summary>
        public static string PHONESNULL {
            get {
                return ResourceManager.GetString("PHONESNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι πόντοι δεν επαρκούν!.
        /// </summary>
        public static string POINTSARENOTENOUGH {
            get {
                return ResourceManager.GetString("POINTSARENOTENOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δε βρέθηκαν τιμοκατάλογοι συνδεμένοι με το κατάστημα για delivery ή take out.
        /// </summary>
        public static string PRICELISTSTORENOFOUND {
            get {
                return ResourceManager.GetString("PRICELISTSTORENOFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι αναντιστοιχίες των τιμών των προϊόντων απέτυχαν.
        /// </summary>
        public static string PRICESMISSMATCHESFAILED {
            get {
                return ResourceManager.GetString("PRICESMISSMATCHESFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το προϊόν &apos;{0}&apos; δεν έχει πρόσθετο &apos;{1}&apos; με κωδ: {2}.
        /// </summary>
        public static string PRODUCTHAVENOEXTRA {
            get {
                return ResourceManager.GetString("PRODUCTHAVENOEXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το προϊόν με κωδ: {0} δε βρέθηκε. (Η περιγραφή του αντικαταστάθηκε με &apos;{1}&apos;).
        /// </summary>
        public static string PRODUCTNOTFOUND {
            get {
                return ResourceManager.GetString("PRODUCTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το προϊόν με κωδ: {0} δε βρέθηκε στον τιμοκατάλογο αναζήτησης. (Η περιγραφή του αντικαταστάθηκε με &apos;{1}&apos;).
        /// </summary>
        public static string PRODUCTNOTFOUNDRICELIST {
            get {
                return ResourceManager.GetString("PRODUCTNOTFOUNDRICELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το ερώτημα με το τρέχον id δεν υπάρχει.
        /// </summary>
        public static string QUERYIDNOTEXIST {
            get {
                return ResourceManager.GetString("QUERYIDNOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η εγγραφή είναι ήδη κλειστή.
        /// </summary>
        public static string REGISTRATIONALREADYCLOSED {
            get {
                return ResourceManager.GetString("REGISTRATIONALREADYCLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η καταχώρηση δεν βρέθηκε.
        /// </summary>
        public static string REGISTRATIONNOTFOUND {
            get {
                return ResourceManager.GetString("REGISTRATIONNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αναφορά επανεκτύπωσης Ζ απέτυχε!.
        /// </summary>
        public static string REPRINTZREPORTFAILED {
            get {
                return ResourceManager.GetString("REPRINTZREPORTFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορεί να γίνει χρέωση δωματίου σε πελάτη που έχει ήδη αναχωρήσει απο το δωμάτιο.
        /// </summary>
        public static string ROOMCHARGEONCHECKEDOUTGUESTDENIED {
            get {
                return ResourceManager.GetString("ROOMCHARGEONCHECKEDOUTGUESTDENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αποθήκευση των διαγραμμένων αρχείων απέτυχε.
        /// </summary>
        public static string SAVEDELETEDFAILED {
            get {
                return ResourceManager.GetString("SAVEDELETEDFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ελλάχιστη παραγγελία δεν μπορεί να είναι μικρότερη του 0.01.
        /// </summary>
        public static string SMALLTOTAL {
            get {
                return ResourceManager.GetString("SMALLTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο Χρήστης δεν έχει αντιστοιχιστεί σε κατάστημα στον DA Server.
        /// </summary>
        public static string STAFFNOASSIGNED {
            get {
                return ResourceManager.GetString("STAFFNOASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κατάστημα είναι κλειστό..
        /// </summary>
        public static string STORECLOSE {
            get {
                return ResourceManager.GetString("STORECLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενδεχομένως να μην έχει εκτυπωθεί ή να μην έχει πληρωθεί ή έχει ήδη ακυρωθεί ή λάθος τύπος παραστατικού!.
        /// </summary>
        public static string STOREDPROCEDUREERRORREASONS {
            get {
                return ResourceManager.GetString("STOREDPROCEDUREERRORREASONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αποθηκευμένη διαδικασία δεν εκτελέστηκε σωστά!.
        /// </summary>
        public static string STOREDPROCEDURENOTEXECUTE {
            get {
                return ResourceManager.GetString("STOREDPROCEDURENOTEXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το StoreId {0} της παραγγελίας διαφέρει από το επιθυμητό! .
        /// </summary>
        public static string STOREIDAUTHFAILDED {
            get {
                return ResourceManager.GetString("STOREIDAUTHFAILDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κατάστημα δεν υποστηρίζει delivery..
        /// </summary>
        public static string STORENODELIVERY {
            get {
                return ResourceManager.GetString("STORENODELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κατάστημα δεν υποστηρίζει τη λήψη παραγγελιών από τον χώρο του καταστηματος.
        /// </summary>
        public static string STORENOTAKEOUT {
            get {
                return ResourceManager.GetString("STORENOTAKEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δε βρέθηκε κατάστημα για την επιλεγμένη διεύθυνση..
        /// </summary>
        public static string STORENOTFOUND {
            get {
                return ResourceManager.GetString("STORENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει αντιστοιχηθεί κατάστημα.
        /// </summary>
        public static string STORENOTMATCHED {
            get {
                return ResourceManager.GetString("STORENOTMATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει αντιστοιχηθεί κατάστημα. Ορίστε πρώτα στη διεύθυνση πελάτη γεωγραφικό μήκος και πλάτος.
        /// </summary>
        public static string STORENOTMATCHED2 {
            get {
                return ResourceManager.GetString("STORENOTMATCHED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κατάστημα αυτή τη στιγμή δεν υποστηρίζει παραγγελίες {0} .
        /// </summary>
        public static string STORENOTSUPPORT {
            get {
                return ResourceManager.GetString("STORENOTSUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το τραπέζι δεν βρέθηκε!.
        /// </summary>
        public static string TABLENOTFOUND {
            get {
                return ResourceManager.GetString("TABLENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βρέθηκαν πολλοί.
        /// </summary>
        public static string TOOMANYFOUND {
            get {
                return ResourceManager.GetString("TOOMANYFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο χρήστης δεν είναι εξουσιοδοτημένος διαχειριστής.
        /// </summary>
        public static string UNAUTHORIZEDADMINUSER {
            get {
                return ResourceManager.GetString("UNAUTHORIZEDADMINUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το email υπάρχει είδη..
        /// </summary>
        public static string UNIQUEEMAIL {
            get {
                return ResourceManager.GetString("UNIQUEEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η μεταβολή απέτυχε.
        /// </summary>
        public static string UPDATEFAILED {
            get {
                return ResourceManager.GetString("UPDATEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εσφαλμένος Κωδικός ή Όνομα Χρήστη.
        /// </summary>
        public static string USERLOGINFAILED {
            get {
                return ResourceManager.GetString("USERLOGINFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο χρήστης {0} δεν βρέθηκε..
        /// </summary>
        public static string USERNOTFOUND {
            get {
                return ResourceManager.GetString("USERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το σύνολο των λεπτομερειών του ΦΠΑ δεν ήταν δυνατό να ταιριάξουν με τη λεπτομέρεια του παραστατικού vatid.
        /// </summary>
        public static string VATDETAILTOTAL {
            get {
                return ResourceManager.GetString("VATDETAILTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο χρήστης είναι ανενεργός.
        /// </summary>
        public static string WEBPOSREPORTSTAFFLOGININACTIVE {
            get {
                return ResourceManager.GetString("WEBPOSREPORTSTAFFLOGININACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχουν εισαχθεί επαρκή διαπιστευτήρια. Απαιτείται η εισαγωγή ονόματος χρήστη και κωδικού.
        /// </summary>
        public static string WEBPOSREPORTSTAFFLOGINNOCREDENTIALS {
            get {
                return ResourceManager.GetString("WEBPOSREPORTSTAFFLOGINNOCREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δε βρέθηκε χρήστης με τα συγκεκριμένα διαπιστευτήρια.
        /// </summary>
        public static string WEBPOSREPORTSTAFFLOGINNOTFOUND {
            get {
                return ResourceManager.GetString("WEBPOSREPORTSTAFFLOGINNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο χρήστης δεν έχει δικαίωμα προβολής των αναφορών.
        /// </summary>
        public static string WEBPOSREPORTSTAFFLOGINUNAUTHORIZED {
            get {
                return ResourceManager.GetString("WEBPOSREPORTSTAFFLOGINUNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος συσχέτιση μεταξύ του Pos και του Client!.
        /// </summary>
        public static string WRONGASSOCIATION {
            get {
                return ResourceManager.GetString("WRONGASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος o κωδικός του Client!.
        /// </summary>
        public static string WRONGCLIENTCODE {
            get {
                return ResourceManager.GetString("WRONGCLIENTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λανθασμένοι κωδικοί πελάτη.
        /// </summary>
        public static string WRONGCUSTOMERIDS {
            get {
                return ResourceManager.GetString("WRONGCUSTOMERIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος Συνολικό Ποσό. υπολογίστηκε {0} αντι για {1}.
        /// </summary>
        public static string WRONGDATOTAL {
            get {
                return ResourceManager.GetString("WRONGDATOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ασυμφωνία Συνολικού Ποσού από e-food (έκπτωση). Yπολογίστηκε {0} αντι για {1}..
        /// </summary>
        public static string WRONGDATOTALEFOOD {
            get {
                return ResourceManager.GetString("WRONGDATOTALEFOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το email δε βρέθηκε.
        /// </summary>
        public static string WRONGEMAIL {
            get {
                return ResourceManager.GetString("WRONGEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος IP!.
        /// </summary>
        public static string WRONGIP {
            get {
                return ResourceManager.GetString("WRONGIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος Κατάστημα.
        /// </summary>
        public static string WRONGSTOREID {
            get {
                return ResourceManager.GetString("WRONGSTOREID", resourceCulture);
            }
        }
    }
}
