//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symposium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symposium.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο λογαριασμός έκλεισε στις: {0}.
        /// </summary>
        public static string ACCOUNTCLOSED {
            get {
                return ResourceManager.GetString("ACCOUNTCLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσθήκη ποσού στον Πιστωτικό Λογαριασμό Barcode.
        /// </summary>
        public static string ADDBARCODEAMOUNT {
            get {
                return ResourceManager.GetString("ADDBARCODEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή χρημάτων για όλους τους λογαριασμούς ανοικτού λογαριασμού.
        /// </summary>
        public static string AMOUNTRETURN {
            get {
                return ResourceManager.GetString("AMOUNTRETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το barcode υπάρχει ήδη στον λογαριασμό.
        /// </summary>
        public static string BARCODEALREADYEXISTS {
            get {
                return ResourceManager.GetString("BARCODEALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το barcode ομαδοποιείται σε άλλο λογαριασμό.
        /// </summary>
        public static string BARCODEGROUPED {
            get {
                return ResourceManager.GetString("BARCODEGROUPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το barcode δεν είναι εγγεγραμμένο.
        /// </summary>
        public static string BARCODENOTREGISTERED {
            get {
                return ResourceManager.GetString("BARCODENOTREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η παραγγελεία {0} δεν μπορεί να αλλάζει γιατί στο κατάστημα έχει εκδοθεί παραστατικό..
        /// </summary>
        public static string CANNOTCHANGEAGENTORDERCOMPLETED {
            get {
                return ResourceManager.GetString("CANNOTCHANGEAGENTORDERCOMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλείσιμο ημέρας.
        /// </summary>
        public static string CLOSINGFODAY {
            get {
                return ResourceManager.GetString("CLOSINGFODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπάρχουν {0} 
        ///ολοκληρωμένες καταχωρήσεις.
        /// </summary>
        public static string COMPLETEDREGISTRATIONS {
            get {
                return ResourceManager.GetString("COMPLETEDREGISTRATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τύπος δεδομένου: {0}.
        /// </summary>
        public static string DATATYPE {
            get {
                return ResourceManager.GetString("DATATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι διπλές τιμές αφαιρέθηκαν.
        /// </summary>
        public static string DUPLICATEVALUESREMOVED {
            get {
                return ResourceManager.GetString("DUPLICATEVALUESREMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εσφαλμένη προσπάθεια Έναρξης Βάρδιας.
        /// </summary>
        public static string INVLADIDCLOCKIN {
            get {
                return ResourceManager.GetString("INVLADIDCLOCKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εσφαλμένη προσπάθεια Λήξης Βάρδιας.
        /// </summary>
        public static string INVLADIDCLOCKOUT {
            get {
                return ResourceManager.GetString("INVLADIDCLOCKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μήκος του string: συμπεριλαμβάνεται μεταξύ {0} και {1}.
        /// </summary>
        public static string LENGTHBETWEEN {
            get {
                return ResourceManager.GetString("LENGTHBETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αντιστοίχιση πρότυπου τύπου έκφρασης: {0}.
        /// </summary>
        public static string MATCHINGPATTERN {
            get {
                return ResourceManager.GetString("MATCHINGPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστο μήκος: {0}.
        /// </summary>
        public static string MAXLENGTH {
            get {
                return ResourceManager.GetString("MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελάχιστο μήκος: {0}.
        /// </summary>
        public static string MINLENGTH {
            get {
                return ResourceManager.GetString("MINLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η κάρτα NFC ανανεώθηκε με επιτυχία!.
        /// </summary>
        public static string NFCCARDUPDATED {
            get {
                return ResourceManager.GetString("NFCCARDUPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καμία υπηρεσία: {0} μπορεί να εφαρμοστεί..
        /// </summary>
        public static string NOSERVICEAPPLIED {
            get {
                return ResourceManager.GetString("NOSERVICEAPPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εύρος: συμπεριλαμβάνεται μεταξύ {0} και {1}.
        /// </summary>
        public static string RANGEBETWEEN {
            get {
                return ResourceManager.GetString("RANGEBETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή υπόλοιπου ποσού στον πελάτη.
        /// </summary>
        public static string REMAININGAMOUNTRETURN {
            get {
                return ResourceManager.GetString("REMAININGAMOUNTRETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αφαίρεση ποσού στον Πιστωτικό Λογαριασμό Barcode.
        /// </summary>
        public static string REMOVEBARCODEAMOUNT {
            get {
                return ResourceManager.GetString("REMOVEBARCODEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to δείγμα string {0}.
        /// </summary>
        public static string SAMPLESTRING {
            get {
                return ResourceManager.GetString("SAMPLESTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπηρεσία: {0} εκτελείται αυτή τη στιγμή..
        /// </summary>
        public static string SERVICECURRENTLYRUNNING {
            get {
                return ResourceManager.GetString("SERVICECURRENTLYRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπηρεσία: {0} ξεκίνησε με επιτυχία..
        /// </summary>
        public static string SERVICESTARTEDSUCCESSFULLY {
            get {
                return ResourceManager.GetString("SERVICESTARTEDSUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λάθος αναγνωριστικό πιστωτικού λογαριασμού.
        /// </summary>
        public static string WRONGCREDITCARD {
            get {
                return ResourceManager.GetString("WRONGCREDITCARD", resourceCulture);
            }
        }
    }
}
